nucleotide-count/nucleotide-count_test.hs
This pull request addresses #58.
The previous tests asserted that, e.g., `count 'X' "ACGT"` would throw an error indicating that `'X'` is not a valid nucleotide. The example implementation performed the same error checking on the strand being counted and on the argument to `nucleotideCounds`, but the tests did not check for this behavior. This PR implements tests that do.
=> nucleotide count: adds strand validation to tests

gigasecond/example.hs, gigasecond/gigasecond_test.hs
=> gigasecond: use times (not dates) for inputs and outputs (#63)

queen-attack/.gitignore, queen-attack/queen-attack_test.hs
This pull request makes some minor improvements to the queen-attack tests by labelling each of the attacks so that failures can be diagnosed.
=> Improved the tests by adding labels for each attack

_test/bootstrap.sh, config.json, lens-person/Person.hs, lens-person/example.hs, lens-person/lens-person_test.hs
This is a relatively easy exercise to play around with basic lenses. It's designed in such a way that lenses aren't actually required, so you can play around with different approaches and see what works best.
@etrepum I haven't made an x-common part for this yet since I wanted to get your opinion on this first. Do you think this is a good exercise for the Haskell track? It does kinda deviate from standard exercism practice by a) (strongly) suggesting the use of non-standard-library libraries and b) being clearly applicable only to Haskell.
=> Add lens-person exercise

docs/ABOUT.md
I realized after the fact that I'd gotten the Quicksort example from "Learn You A Haskell", so I added a link.
=> Added attribution link to the source of the quicksort example in ABOUT.md

largest-series-product/example.hs, largest-series-product/largest-series-product_test.hs
As part of the work to have consistency between tracks as in https://github.com/exercism/todo/issues/104 and https://github.com/exercism/todo/issues/13. Comments are in individual commit messages.
=> largest-series-product corner cases

gigasecond/gigasecond_test.hs
Apparently `System.Locale` get deprecated on haskell 7.10 and moved to the package `old-locale-1.0.0.7`.
And this change will use reuse the function provided by `Data.Time.Format`
Ref: https://github.com/exercism/xhaskell/issues/85#issuecomment-191382840
=> gigasecond: fix use of deprecated package

largest-series-product/example.hs, largest-series-product/largest-series-product_test.hs
The digits and slices functions are internal implementation details and
thus the test case for the largest-series-product problem should not be
concerned with testing them. The series tests could potentially be moved
to the series exercise (already implemented by this track).
Their presence may cause students to falsely think that their solution
has to use these two functions, instead of the alternative
implementation of only iterating through the digits once.
If it is desired to give hints on how to approach this problem (which
was one advantage of having the digits and slices tests), then consider
including a hints file and/or directory in the largest-series-product
directory.
This PR arises from discussion in
https://github.com/exercism/x-common/issues/192
=> largest-series-product: Do not test digits/slices

sum-of-multiples/example.hs, sum-of-multiples/sum-of-multiples_test.hs
=> sum-of-multiples: Explicitly pass [3, 5] instead of defaulting

SETUP.md
help.exercism.io was deprecated sometime around December 2015.
Closes #104
=> SETUP.md: link to exercism Haskell page not help.exercism.io

config.json, exercises/hamming/example.hs, exercises/hamming/hamming_test.hs, exercises/point-mutations/example.hs
point-mutations was deprecated in favor of hamming a while ago (to make
it more generic, since it really was just about Hamming distance rather
than specifically about biological applications)
Since the module is now named Hamming, the function hammingDistance is
renamed to distance so as to not be repetitive (Hamming.distance versus
Hamming.hammingDistance)
Fixes #95
=> rename point-mutations to hamming

.travis.yml
I submitted #121 to try to see why we didn't use `language: haskell`.
I got my answer, and now it's a good idea to record why so that we will
know when we are able to re-evaluate our options.
Closes #123.
=> travis: Explain why we use hvr-ghc

exercises/phone-number/phone-number_test.hs
Required because always returning hard-coded 1234567890 should not pass
the tests. See my iteration here:
http://exercism.io/submissions/0d92454ef01942c19ba05e82bd4338db
=> Adds more cases to phone-number tests

exercises/binary-search-tree/binary-search-tree_test.hs, exercises/binary-search-tree/example.hs
Since #59 mentioned that it was surprising that binary search trees in this exercise couldn't be empty (since `bstValue` was of type `BST a -> a` rather than `BST a -> Maybe a`) I explored what it would be like if it was allowed.
Unfortunately, now that `data BST` has two variants and is no longer a record, we no longer get "free" implementations of `bstValue`, `bstLeft`, and `bstRight`. However, I found this better than the alternatives:
* `newtype BST a = BST (Maybe (Node a))` means you have to litter `fromBST` and `BST` in various places to convert to/from the `newtype`. I didn't particularly like this, but you can examine this at [my bst-empty-newtype branch](https://github.com/exercism/xhaskell/compare/master...petertseng:bst-empty-newtype?expand=1)
* `type BST a = Maybe (Node a)` …
=> binary-search-tree: Allow empty trees

.gitignore
beam is for Erlang, which has nothing to do with Haskell.
First discovered in
https://github.com/exercism/xrust/pull/129#discussion_r64982860
=> gitignore: rm beam

docs/INSTALLATION.md
This PR adds some installation instructions for the stack tool. It
explains briefly how to install stack (links to the stack
documentations) and how to use it to run the tests in each exercise.
=> Add Stack instructions to installation.md

exercises/atbash-cipher/atbash-cipher_test.hs, exercises/binary/binary_test.hs, exercises/crypto-square/crypto-square_test.hs, exercises/hexadecimal/hexadecimal_test.hs, exercises/largest-series-product/largest-series-product_test.hs, exercises/nth-prime/nth-prime_test.hs, exercises/prime-factors/prime-factors_test.hs, exercises/raindrops/raindrops_test.hs, exercises/roman-numerals/roman-numerals_test.hs, exercises/scrabble-score/scrabble-score_test.hs, exercises/triangle/triangle_test.hs
Some exercises show a warning when compiling the test module:
```
Defined but not used: `testCase`
```
This can confuse users and is not considered good practice.
Unused code:
- function `testCase`
- import of `Assertion`
Affected exercises:
- atbash-cipher
- binary
- crypto-square
- hexadecimal
- largest-series-product
- nth-prime
- prime-factors
- raindrops
- roman-numerals
- scrabble-score
- triangle
Closes #145
=> Remove unused function testCase generating warning when compiling test modules.

exercises/grains/grains_test.hs, exercises/hamming/hamming_test.hs, exercises/leap/leap_test.hs, exercises/pascals-triangle/pascals-triangle_test.hs, exercises/scrabble-score/scrabble-score_test.hs, exercises/sieve/sieve_test.hs, exercises/sum-of-multiples/sum-of-multiples_test.hs
In some problems, like `leap`, the test module doesn't declare explicitly some numeric types, allowing solutions with multiple types:
```haskell
isLeapYear :: Int     -> Bool
isLeapYear :: Integer -> Bool
```
This is desirable, but has the unintended effect of displaying the warning...
```
Defaulting the following constraint(s) to type `Integer` arising from the use of `isLeapYear` at leap_test.hs ... arising from the literal 1996 ...
```
... when compiling `leap_test.hs` with polymorphic solutions:
```haskell
isLeapYear :: Integral a => a -> Bool
```
It's important to suppress this warning so we don't misguide newcomers in thinking that there is something wrong with their code, when the problem is in the test module. Also, using the most general type is actually encouraged in Haskell. …
=> Add -fno-warn-type-defaults to supress unwanted warnings.

exercises/binary/binary_test.hs
"carrot123" was too coarse-grained. We'd instead like to test alphabetic
characters at the beginning, middle, and end of otherwise-valid numbers.
The test for digits such as 2 should also come in a separate test.
Closes #111
=> binary: Expand invalid input tests

exercises/triangle/triangle_test.hs
The existing tests missed a case where the two smaller sides were equal. A lot of solutions involved sorting the input, so this matters.
=> added test case for isosceles triangle

.travis.yml, exercises/binary-search-tree/example.hs, exercises/custom-set/example.hs
It's a prerelease version, but it's likely to be good to start testing
against it now.
Two commits are needed to avoid compiler warnings on 8.0.1 (and thus errors since we use `-Werror`). The errors that would appear are noted in the commit message.
=> travis: Test ghc 8.0.1 (and avoid some compiler warnings on 8.0.1)

.travis.yml
This will decrease install times
Closes #119
=> travis: Install only the GHC we are testing

_test/check-exercises.hs
This fixes the warning *"The import of Control.Applicative is redundant"* when compiling `check-exercises` caused by `Prelude` re-exporting `Control.Applicative.<$>` in `base >= 4.8`.
Removing the offending line is undesirable because it would break compiling if `ghc <= 7.10`.
Closes #122
=> check-exercises: Fix warning with ghc >= 7.10.

exercises/clock/clock_test.hs
Add test to match x-common/clock.json.
Remove legacy tests.
Closes #125
=> clock: Update to match x-common/clock.json

.gitignore
Add new entries to .gitignore to make move convenient for
contributors to use alternative build methods.
- Default .ignore exclusions for Haskell from GitHub.
- Exclusions for development with cabal-sandboxes, stack and hpack.
- Reordering.
=> New .gitignore based on GitHub's default.

exercises/phone-number/example.hs, exercises/phone-number/phone-number_test.hs
Signaling invalid input to phone number parsing by returning a Nothing
instead of a string of 0's. This better represents idiomatic haskell,
and also signifies a difference between an input of all 0's and an
invalid input.
Closes #158
=> Changing return types for phone-number exercise to be Maybes

README.md, _test/dependencies, _test/dependencies.txt, _test/stackalize
Install three files:
- `dependencies.txt` - List of dependencies for all Haskell sources.
- `dependencies` - Shell script to query dependencies.
- `stackalize` - Shell script to convert an exercise in a stack project.
Sample usage:
```
$ dependencies go-counting
array
base
containers
HUnit
$ dependencies `ls exercises`
array
attoparsec
...
time
vector
$ dependencies --only-in-examples `ls exercises`
attoparsec
lens
..
split
stm
$ cd exercises/leap
$ stackalize --resolver lts-6.4
...
$ stack test
$ stackalize --undo
```
Closes #151
=> Add haskell exercises' dependency control.

exercises/rna-transcription/DNA.hs, exercises/rna-transcription/example.hs, exercises/rna-transcription/rna-transcription_test.hs
- Error case is now defined, eliminating the desire to throw an `error`
for invalid input.
- The test and example solution are more idiomatic to Haskell, using a
`Maybe`.
Closes #166
=> rna-transcription: Changes return type to Maybe

README.md
Whether this is necessary depends on whom we are targeting with this
README. If we think everyone reading it already knows what it means to
add to the PATH, then we don't need this.
This commit, if we merge it, does not make that assumption, so we
explain why someone might want to add _test to path.
It's noted that the README doesn't provide instructions on how to add
something to the PATH but this would be a tricky endeavor as the way to
do so may differ, so we'd have to discuss it.
=> README: Explain significance of adding _test to path

_test/dependencies.txt
Add `containers` to `rna-transcription/example.hs` dependencies.
=> rna-transcription: Fix missing dependency cause by exercism/xhaskell#168.

exercises/nucleotide-count/example.hs, exercises/nucleotide-count/nucleotide-count_test.hs
The resulting exercise is more idiomatic to Haskell. The `Either` will provide a useful error message to end users of the functions.
Closes #157
=> Updating the Nucleotide Count exercise to return Either

_test/dependencies.txt, config.json, exercises/all-your-base/Base.hs, exercises/all-your-base/all-your-base_test.hs, exercises/all-your-base/example.hs
Add the tests, an example solution and a stub.
Add exercise to `config.json`, after `atbash-cipher`.
Add dependencies to `dependencies.txt`.
Closes #167
=> all-your-base: Add new exercise

_test/bootstrap.sh
Thanks to #159, we have a list of dependencies of each exercise. We
should replace the current hard-coded list in `bootstrap.sh` with one
inferred from `dependencies.txt`.
Closes #175
=> bootstrap: Use dependencies.txt to list packages

.travis.yml, _test/bootstrap.sh
The work in #162 is advantageous because we can check our dependencies
and have hermetic builds (do not break on upstream changes).
One question about whether to merge it was the necessity to drop GHC
7.6.
This commit introduces to Travis the ability to test with either Stack
or without (the old way of doing things). We test 7.6, 7.8, 7.10, 8.0
with cabal-install as we did before, and also Stack as done in #162.
Closes #162 (is based on it)
Closes #124 (explanatory comments provided)
Closes #153 (based on #162 which also closed #153)
=> travis: test both Stack and non-stack (Cabal)

exercises/simple-linked-list/simple-linked-list_test.hs
Otherwise, an implemenation of isNil that returned True all the time
would pass the tests
=> Simple Linked List: Add a handful of tests that assert isNil returns False

exercises/all-your-base/all-your-base_test.hs
Make it possible to easily comment out the test cases so that the problem can be
solved iteratively by moving the commas in the vertical list to the start of the
line.
=> all-your-base: Fix test formatting

exercises/hamming/Hamming.hs, exercises/hamming/example.hs, exercises/hamming/hamming_test.hs
- Change return type of `distance` to a *Maybe*.
- Rewrite tests to match `exercism/x-common/hamming.hs`.
=> hamming: Change return to Maybe and match json

exercises/grains/Grains.hs, exercises/grains/example.hs, exercises/grains/grains_test.hs
Currently, the exercise `grains` has a function `square :: Int -> Integer` that returns the number of grains of wheat on sequentially numbered squares on a chessboard. The problem doesn't specify what should be returned if the number given is not in the chessboard.
This is a great opportunity to make it more idiomatic and get the users acquainted with `Maybe`.
I propose to to the following: 
1. Change the return type of function `square` from an `Integer` to a `Maybe Integer`.
2. Add three test:
- `square (-1)`
- `square   0`
- `square  65`
3. Add a stub solution.
=> grains: Change return type to Maybe

exercises/etl/ETL.hs, exercises/etl/etl_test.hs, exercises/etl/example.hs
The `etl` exercise uses `String` to represent each letter in both, the input and the output of `transform`.
This is unidiomatic because, in Haskell, a single haracter is not the same type as a list of characters.
To avoid exposing users to unidiomatic code and ease understanding of what is being asked in this exercise, I propose the following changes:
1. Change letter representation from String to Char.
2. Add stub solution.
=> etl: Change letter representation to Char

README.md, SETUP.md, docs/INSTALLATION.md, docs/TESTS.md
Rewrite `./README.md`
Rewrite `./SETUP.md`
Rewrite `./INSTALLATION.md`
Rewrite `./TESTS.md`
=> Transform exercises in Stack projects - Phase 5 - Creating the final documentation

exercises/queen-attack/src/Queens.hs
Taking the suggestions of https://github.com/exercism/xhaskell/pull/200/files#r71086758
into account, it seemed prudent to explain enough so that it is clear
from just looking at the stub file what is expected. This seems to be in
line with the goals of #181 which explains that we wish to save users
from inspecting the test suites to figure out what they need to
implement.
=> queen-attack: Explain positions and white/black

exercises/strain/test/Tests.hs
Just as d238a331c2bccaa1d86522198e0a85235a6356d6 added a test for
accumulate to be non-strict, we add a test for keep and discard that
does the same.
For the purpose of #194
Closes #208
=> strain: Add test for non-strict keep and discard

exercises/accumulate/src/Example.hs
The intent, I believe, is to show an example that would work and gives
correct results but fails the non-strictness test. It was added in
d238a331c2bccaa1d86522198e0a85235a6356d6.
In order for it to compile, the `xs` needs to be removed (an eta
reduction has happened).
In order for the results to be correct, final `acc` must be reversed.
=> accumulate: fix inefficient example

exercises/sublist/package.yaml, exercises/sublist/test/Tests.hs
- Rewrite to use hspec.
- Add tests to match the json file.
- Remove most of the tests not matching the json file.
=> sublist: Rewrite tests to use hspec with fail-fast.

exercises/grains/package.yaml, exercises/grains/test/Tests.hs
=> grains: Rewrite tests to use hspec with fail-fast.

exercises/gigasecond/package.yaml, exercises/gigasecond/test/Tests.hs
=> gigasecond: Rewrite tests to use hspec with fail-fast.

exercises/bob/package.yaml, exercises/bob/src/Example.hs, exercises/bob/test/Tests.hs
- Rewrite to use hspec.
- Add tests to match the json file.
- Remove old test not matching the json file.
- Fix solution to work with the new test cases.
=> bob: Rewrite tests to use hspec with fail-fast.

exercises/sum-of-multiples/package.yaml, exercises/sum-of-multiples/test/Tests.hs
=> sum-of-multiples: Rewrite tests to use hspec with fail-fast.

exercises/rna-transcription/package.yaml, exercises/rna-transcription/test/Tests.hs
=> rna-transcription: Rewrite tests to use hspec with fail-fast.

exercises/anagram/package.yaml, exercises/anagram/test/Tests.hs
- Rewrite to use hspec.
- Update to match the json file.
=> anagram: Rewrite to use hspec with fail-fast.

exercises/nucleotide-count/package.yaml, exercises/nucleotide-count/test/Tests.hs
- Rewrite to use hspec with fail-fast.
- Change tests to make them more polymorphic.
=> nucleotide-count: Rewrite to use hspec with fail-fast.

exercises/simple-linked-list/package.yaml, exercises/simple-linked-list/test/Tests.hs
=> simple-linked-list: Rewrite tests to use hspec with fail-fast.

exercises/list-ops/package.yaml, exercises/list-ops/test/Tests.hs
=> list-ops: Rewrite tests to use hspec with fail-fast.

exercises/etl/package.yaml, exercises/etl/test/Tests.hs
=> etl: Rewrite tests to use hspec with fail-fast.

exercises/robot-name/package.yaml, exercises/robot-name/test/Tests.hs
=> robot-name: Rewrite tests to use rspec with fail-fast.

exercises/meetup/package.yaml, exercises/meetup/test/Tests.hs
=> meetup: Rewrite tests to use hspec with fail-fast.

exercises/beer-song/package.yaml, exercises/beer-song/test/Tests.hs
=> beer-song: Rewrite tests to use hspec with fail-fast.

exercises/triangle/package.yaml, exercises/triangle/test/Tests.hs
=> triangle: Rewrite test do use hspec with fail-fast.

exercises/scrabble-score/package.yaml, exercises/scrabble-score/src/Example.hs, exercises/scrabble-score/test/Tests.hs
- Rewrite example to accept json tests.
=> scrabble-score: Rewrite tests to use hspec with fail-fast.

exercises/roman-numerals/package.yaml, exercises/roman-numerals/test/Tests.hs
=> roman-numerals: Rewrite tests to use hspec with fail-fast.

config.json
Dicussion in #192 indicates it is safe to do so.
Sidesteps having to change these for #115.
As part of https://github.com/exercism/x-common/issues/279
=> config: deprecate binary, trinary, octal, hexadecimal

exercises/binary/package.yaml, exercises/binary/test/Tests.hs
- Update tests to match the json file.
- Fix test descriptions mentioning "errors".
=> binary: Rewrite tests to use hspec with fail-fast.

exercises/raindrops/package.yaml, exercises/raindrops/test/Tests.hs
- Rewrite test to use hspec
- Remove test not matching x-common.
=> raindrops: Rewrite tests to use hspec with fail-fast.

exercises/prime-factors/package.yaml, exercises/prime-factors/test/Tests.hs
=> prime-factors: Rewrite tests to use hspec with fail-fast.

exercises/allergies/package.yaml, exercises/allergies/test/Tests.hs
- Fixed to allow allergens to be returned in any order.
- Fixed to supress warning on polymorphic solutions.
=> allergies: Rewrite tests to use hspec with fail-fast.

exercises/all-your-base/package.yaml, exercises/all-your-base/test/Tests.hs
=> all-your-base: Rewrite tests to use hspec with fail-fast.

exercises/atbash-cipher/package.yaml, exercises/atbash-cipher/src/Atbash.hs, exercises/atbash-cipher/src/Example.hs, exercises/atbash-cipher/test/Tests.hs
- Update tests to match `x-common`.
- Add `decode` function to the tests.
- Add `decode` to the stub solution.
- Rewrite the example solution to pass the new tests.
=> atbash-cipher: Rewrite tests to use hspec with fail-fast.

exercises/luhn/package.yaml, exercises/luhn/test/Tests.hs
=> luhn: Rewrite tests to use hspec with fail-fast.

exercises/largest-series-product/package.yaml, exercises/largest-series-product/src/Example.hs, exercises/largest-series-product/test/Tests.hs
- Update tests to match `x-common`.
- Rewrite example solution to pass the tests.
=> largest-series-product: Rewrite tests to use hspec with fail-fast.

exercises/hexadecimal/package.yaml, exercises/hexadecimal/test/Tests.hs
=> hexadecimal: Rewrite tests to use hspec with fail-fast.

exercises/difference-of-squares/package.yaml, exercises/difference-of-squares/src/Squares.hs, exercises/difference-of-squares/test/Tests.hs
- Update tests to match `x-common`
- Rewrite tests for an `Integral` implementation.
- Add `Integral` type signatures to stub solution.
=> difference-of-squares: Rewrite tests to use hspec with fail-fast.

exercises/binary-search-tree/package.yaml, exercises/binary-search-tree/test/Tests.hs
=> binary-search-tree: Rewrite tests to use hspec with fail-fast.

exercises/queen-attack/package.yaml, exercises/queen-attack/test/Tests.hs
- Update `canAttack` tests to match `x-common`
- Suppress test suite warning on polymorphic solutions.
The exercise matches only partially the JSON file, because it doesn't have a functions to create queens. That function would probably make more sense in a object-oriented language, but seems artificial here.
Also, the coordinate system used is artificial for chess players. Maybe the JSON file deserves a rewrite to remove the `create` function and use a **right-up** orientation starting on **(1, 1)**, as explained in [this comment](https://github.com/exercism/x-common/issues/313#issuecomment-236798084).
=> queen-attack: Rewrite tests to use hspec with fail-fast.

exercises/robot-simulator/package.yaml, exercises/robot-simulator/src/Example.hs, exercises/robot-simulator/src/Robot.hs, exercises/robot-simulator/test/Tests.hs
- Remove old tests.
- Add tests to match `x-common`.
- Remove import of `Robot` in test suite.
- Remove export of `Robot` in example solution.
- Remove export of `Robot` in stub solution.
- Remove instructions to derive `(Eq, Ord)` in stub.
This exercise is too distant from what is defined in `x-common`, so it will probably be good to rewrite it. I tried to leave comments about the deviations to make the task easier.
I also simplified the interface so that it's not necessary to export the `Robot` data type. This is recommended for better modularization and allows more creative solutions.
=> robot-simulator: Rewrite tests to use hspec with fail-fast.

exercises/crypto-square/package.yaml, exercises/crypto-square/src/CryptoSquare.hs, exercises/crypto-square/src/Example.hs, exercises/crypto-square/test/Tests.hs
- Remove old tests.
- Add tests to match `x-common`.
- Remove function `squareSize` from the test suite.
- Remove function `squareSize` from the stub solution.
- Remove function `squareSize` from example's export list.
=> crypto-square: Rewrite tests to use hspec with fail-fast.

exercises/house/package.yaml, exercises/house/test/Tests.hs
- Remove use of `unlines`.
Considering that this exercise is about refactoring, the test suite should contain the most crude representation of the song, so we avoid `unlines` to let the user figure that out.
=> house: Rewrite tests to use hspec with fail-fast.

exercises/clock/package.yaml, exercises/clock/test/Tests.hs
=> clock: Rewrite tests to use hspec with fail-fast.

exercises/minesweeper/package.yaml, exercises/minesweeper/test/Tests.hs
=> minesweeper: Rewrite tests to use hspec with fail-fast.

exercises/ocr-numbers/package.yaml, exercises/ocr-numbers/test/Tests.hs
=> ocr-numbers: Rewrite tests to use hspec with fail-fast.

exercises/food-chain/package.yaml, exercises/food-chain/test/Tests.hs
=> food-chain: Rewrite tests to use hspec with fail-fast.

exercises/trinary/package.yaml, exercises/trinary/test/Tests.hs
=> trinary: Rewrite tests to use hspec with fail-fast.

exercises/queen-attack/src/Queens.hs
In #207 the comment was added, but the comment was incorrect compared to
what the test cases were testing. This commit repairs the comment to
match the tests.
All four corners of the board are specified to make this abundantly
clear.
Closes #276
=> queen-attack: switch row/column in comment

config.json
=> gigasecond: Deprecate exercise.

.travis.yml
This removes integration tests for unused Stack snapshots in Travis CI. Only the current snapshot and `nightly` will be automatically tested.
Compatibility code in the test suites can now be removed safely.
Closes #264.
=> travis: Drop compatibility with old Stack snapshots.

exercises/custom-set/package.yaml, exercises/custom-set/test/Tests.hs
- Remove explicit testing of `Show`.
=> custom-set: Rewrite tests to use hspec with fail-fast.

exercises/minesweeper/package.yaml, exercises/minesweeper/src/Example.hs, exercises/minesweeper/test/Tests.hs
- Update tests to match `x-common`.
- Rewrite example solution to pass the new tests.
Closes #273.
=> Minesweeper match json

exercises/nth-prime/package.yaml, exercises/nth-prime/src/Example.hs, exercises/nth-prime/test/Tests.hs
- Update tests to match exercism/x-common#332.
- Change return type to Maybe.
=> nth-prime: Rewrite tests to use hspec with fail-fast.

exercises/palindrome-products/HINTS.md, exercises/palindrome-products/package.yaml, exercises/palindrome-products/src/Palindromes.hs, exercises/palindrome-products/test/Tests.hs
- Add `HINTS.md`.
- Move old hints to `HINTS.md`.
- Update the stub solution.
We took the opportunity to use this PR as a first experiment with `HINTS.md` in the Haskell track.
=> palindrome-products: Rewrite tests to use hspec with fail-fast.

config.json
This addresses issue #274
https://github.com/exercism/xhaskell/issues/274
=> Update config.json to new specification

exercises/pig-latin/package.yaml, exercises/pig-latin/src/Example.hs, exercises/pig-latin/test/Tests.hs
- Rewrite test to use `hspec`.
- Update the tests to match `x-common`.
- Patch the example solution to pass the new tests.
=> pig-latin: Rewrite tests to use hspec with fail-fast.

exercises/pythagorean-triplet/package.yaml, exercises/pythagorean-triplet/test/Tests.hs
=> pythagorean-triplets: Rewrite tests to use hspec with fail-fast.

exercises/saddle-points/package.yaml, exercises/saddle-points/test/Tests.hs
=> saddle-points: Rewrite tests to use hspec with fail-fast.

exercises/series/package.yaml, exercises/series/test/Tests.hs
=> series: Rewrite tests to use hspec with fail-fast.

exercises/pascals-triangle/package.yaml, exercises/pascals-triangle/src/Example.hs, exercises/pascals-triangle/src/Triangle.hs, exercises/pascals-triangle/test/Tests.hs
- Rename function `triangle` to `rows`
- Change tests do expect `row` to count lines starting at zero.
- Rewrite the stub solution to be more concise and match the new test suite.
~~Considering that there is a ongoing discussion in exercism/x-common#362, I think we should wait it before merging this PR.~~
=> pascals-triangle: Rewrite tests to use hspec with fail-fast.

exercises/series/src/Example.hs, exercises/series/test/Tests.hs
This seems a useful case to test. There is one series of size zero in
all series.
The solution does need to be changed here, otherwise it would have said
that `series 0 "012"` was `[[],[],[]]` instead of `[[]]`.
=> series: Test series of zero

exercises/sieve/package.yaml, exercises/sieve/test/Tests.hs
=> sieve: Rewrite tests to use hspec with fail-fast.

exercises/secret-handshake/HINTS.md, exercises/secret-handshake/package.yaml, exercises/secret-handshake/src/SecretHandshake.hs, exercises/secret-handshake/test/Tests.hs
=> secret-handshake: Rewrite tests to use hspec with fail-fast.

exercises/say/package.yaml, exercises/say/test/Tests.hs
=> say: Rewrite tests to use hspec with fail-fast.

exercises/simple-cipher/package.yaml, exercises/simple-cipher/test/Tests.hs
This is supposed to be an almost literal translation from `HUnit` to `hspec`.
=> simple-cipher: Rewrite tests to use hspec with fail-fast.

exercises/parallel-letter-frequency/HINTS.md, exercises/parallel-letter-frequency/package.yaml, exercises/parallel-letter-frequency/src/Frequency.hs, exercises/parallel-letter-frequency/test/Tests.hs
=> parallel-letter-frequency: Rewrite tests to use hspec with fail fast.

exercises/connect/package.yaml, exercises/connect/src/Connect.hs, exercises/connect/src/Example.hs, exercises/connect/test/Tests.hs
- Update tests to match `x-common`.
- Rename `Color(Black,White)` to `Mark(Cross,Nought)`
- Patch the example and the stub solutions to use the new names.
Now all the tests match `x-common` almost exactly. The only difference is that I kept the expected value as an *ADT*, not a *String* containing `X` or `O`.
Also, I had to change the ADT to have more meaningful names - how would anyone know that `X` was `Black` - so I borrowed them from [Tic-tac-toe's Wikipedia page](https://en.wikipedia.org/wiki/Tic-tac-toe). The alternative would be to use `X` and `O`, but I'm not sure if it is a good idea to have single letter data constructors.
I can change the ADT if someone comes with better names.
Also, considering that we are breaking compatibility …
=> connect: Rewrite test to use hspec with fail-fast.

exercises/sgf-parsing/HINTS.md, exercises/sgf-parsing/package.yaml, exercises/sgf-parsing/src/Sgf.hs, exercises/sgf-parsing/test/Tests.hs
- Move hints to `HINTS.md`.
- Rewrite tests to use `hspec` with *fail-fast*.
=> sgf-parsing: Rewrite tests to use hspec with fail-fast.

exercises/nth-prime/test/Tests.hs
Related to merging exercism/x-common#332.
=> nth-prime: Fix comment to say that is matches x-common.

exercises/bank-account/HINTS.md, exercises/bank-account/src/BankAccount.hs, exercises/bank-account/test/Tests.hs
=> bank-account: Move hints to HINTS.md

exercises/roman-numerals/HINTS.md, exercises/roman-numerals/src/Example.hs, exercises/roman-numerals/test/Tests.hs
- Change test suite to expect a `Maybe`.
- Add `HINTS.md` do explain what is expected in a solution.
- Patch the example solution to return `Just` values.
Closes #304.
=> roman-numerals: Change return type to a Maybe

exercises/clock/HINTS.md, exercises/clock/src/Clock.hs, exercises/clock/test/Tests.hs
=> clock: Move hints to HINTS.md

exercises/queen-attack/HINTS.md, exercises/queen-attack/src/Queens.hs
=> queen-attack: Move hints to HINTS.md

exercises/forth/HINTS.md, exercises/forth/src/Forth.hs
=> forth: Move hints to HINTS.md

exercises/go-counting/HINTS.md, exercises/go-counting/src/Counting.hs, exercises/go-counting/test/Tests.hs
=> go-counting: Move hints to HINTS.md

exercises/custom-set/HINTS.md, exercises/custom-set/src/CustomSet.hs, exercises/custom-set/test/Tests.hs
=> custom-set: Move hints to HINTS.md

exercises/food-chain/HINTS.md, exercises/food-chain/src/Example.hs, exercises/food-chain/src/FoodChain.hs, exercises/food-chain/test/Tests.hs
- Use lyrics from `x-common/exercises/food-chain/canonical-data.json`.
- Tests all lines, one by one, and then the entire song.
- Add stub solution passing the tests.
- Patch example solution to work with the new tests.
This is a first try at solving #301. When we get this right, we may extend the same logic to `beer-song` and `house`.
There is some magic in the test suite to check the lyrics line by line, but I couldn't find a better way to write it.
The stub solution has the complete lyrics in the most raw form possible, so that the student will be forced to refactor everything from zero.
The previous tests suite had an empty line at the end, but that makes no sense and doesn't match the reference file.
=> food-chain: Rewrite tests and add working stub solution.

README.md, docs/TESTS.md
- Change sample code in `docs/TESTS.md` to use `hspec`.
- Change text in `docs/TESTS.md` to match the fact that all
exercises now have *stub solutions*.
- Change `README.md` to include `HINTS.md` file in exercise's
structure.
=> documentation: Fix to match hspec and HINTS.md files.

SETUP.md, docs/TESTS.md
This may be redundant, considering that we already ask for a Stack version greater than 1.1.2 in `INSTALLATION.md`, but some users try to run the tests with older versions, so it makes sense to keep this for a while.
Closes #272.
=> documentation: Instructions for "No .cabal file"

exercises/house/HINTS.md, exercises/house/src/Example.hs, exercises/house/src/House.hs, exercises/house/test/Tests.hs
- Add `HINTS.md` explaining that this exercise is about refactoring.
- Add a stub solution that passes the tests.
- Remove extra newline in the tests to match `description.md` in `x-common`.
- Patch example solution to pass the new tests.
Related to #301.
=> house: Fix tests to match x-common and add working stub solution.

exercises/go-counting/package.yaml, exercises/go-counting/test/Tests.hs
- Completely rewrite tests to use `hspec`.
- Add test suite's dependency on package `multiset`.
This was one of the most challenging re-writings since we started migrating the exercises to `hspec`, so I think I owe a few explanations:
- `shouldScore` is pointfree madness, but I couldn't make it more readable any other way.
- `toOccurList . fromOccurList` is the best way I could find to sum all the scores.
- `first` and `swap` are not commonly used in this repository, but I think they really make sense.
=> go-counting: Rewrite tests to use hspec with fail-fast.

README.md
*HLint* usually gives good suggestions to improve coding style, so we are creating a short section in `README.md` recommending contributors to run it before every submission.
=> documentation: Add HLint to README.md

README.md
Running `stack test --pedantic` will not recompile unchanged
source code already compiled with warnings.
To be really sure that everything compiles correctly without
warnings, it is necessary to first run `stack clean`.
=> documentation: Update README.md with more detailed test instrucions.

exercises/list-ops/src/Example.hs
The following hint should be ignored, because it would create an
example solution implementing a custom `foldr` with
`Prelude.foldr`, which is against the purpose of this exercise.
```
./src/Example.hs:24:5: Suggestion: Use foldr
Found:
go [] = x0
go (x : xs) = x `f` go xs
Why not:
go xs = foldr f x0 xs
1 hint
```
=> list-ops: Improve code based on HLint's suggestions.

exercises/pov/src/Example.hs, exercises/pov/test/Tests.hs
=> pov: Improve code based on HLint's suggestions.

exercises/list-ops/src/Example.hs
As part of #355
If we are to run HLint in Travis, we'll need to tell it that it's
acceptable to not use foldr here. We don't want to use foldr since this
exercise is about implementing it!
=> list-ops: Ignore HLint's hint to use foldr

exercises/hexadecimal/src/Example.hs
The following hint makes the function less readable:
```
./src/Example.hs:5:5: Warning: Use isDigit
Found:
c >= '0' && c <= '9'
Why not:
isDigit c
1 hint
```
=> hexadecimal: Supress HLint's suggestion to use isDigit.

exercises/linked-list/test/Tests.hs
The following suggestions would probably make the tests shorter, but harder to read:
```
./test/Tests.hs:16:7: Suggestion: Reduce duplication
Found:
deque <- mkDeque
push deque 'a'
push deque 'b'
Why not:
Combine with ./test/Tests.hs:23:7
./test/Tests.hs:16:7: Suggestion: Reduce duplication
Found:
deque <- mkDeque
push deque 'a'
push deque 'b'
pop deque `shouldReturn` Just 'b'
Why not:
Combine with ./test/Tests.hs:44:7
./test/Tests.hs:30:7: Suggestion: Reduce duplication
Found:
deque <- mkDeque
unshift deque 'a'
unshift deque 'b'
Why not:
Combine with ./test/Tests.hs:37:7
3 hints
```
It is not clear why, but `hlint` doesn't supresses the suggestions if we use `{-# ANN specs ...`, only with `{-# ANN module ...`.
=> linked-list: Supress HLint's suggestions to reduce duplication.

exercises/trinary/HINTS.md, exercises/trinary/test/Tests.hs
=> trinary: Move hints to HINTS.md

exercises/octal/HINTS.md, exercises/octal/test/Tests.hs
=> octal: Move hints to HINTS.md

exercises/rna-transcription/src/DNA.hs
In #302, we are moving all the hints in the test suites and stub solutions to `HINTS.md` files. But the comments in `src/DNA.hs` are too obvious and may take all the fun of solving the exercise, so we are just removing them.
=> rna-transcription: Remove unneeded stub comments.

exercises/bank-account/test/Tests.hs
The following suggestion would probably make the tests
shorter, but harder to read:
```
./test/Tests.hs:29:9: Suggestion: Reduce duplication
Found:
account <- openAccount
getBalance account `shouldReturn` Just 0
incrementBalance account 10 `shouldReturn` Just 10
Why not:
Combine with ./test/Tests.hs:47:9
1 hint
```
It is not clear why, but `hlint` doesn't supresses the suggestions
if we use `{-# ANN specs ...`, only with `{-# ANN module ...`.
=> bank-account: Supress HLint suggestion

exercises/robot-name/src/Example.hs, exercises/robot-name/test/Tests.hs
- Remove variable named `pattern` in `src/Example` to workaround HLint's bug that causes a parse error.
```
./src/Example.hs:19:31: Error: Parse error: pattern
Found:
generateName :: IO String
> generateName = mapM randomRIO pattern
where pattern = [ letter, letter, digit, digit, digit ]
letter = ('A', 'Z')
```
- Simplify code with `fmap`, as suggested.
```
./src/Example.hs:10:11: Suggestion: Use fmap
Found:
generateName >>= newMVar >>= return . Robot
Why not:
fmap Robot (generateName >>= newMVar)
```
- Supress warning to reduce code duplication that would harm readability.
```
./test/Tests.hs:34:13: Warning: Reduce duplication
Found:
n1 <- robotName r
n2 <- robotName r
n3 <- robotName r
n1 `shouldBe` n2
n1 `shouldBe` n3
Why not:
Combine with ./test/Tests.hs:53:13
```
=> robot-name: Fix HLint's suggestions and errors

exercises/lens-person/package.yaml, exercises/lens-person/src/Person.hs, exercises/lens-person/test/Tests.hs
- Remove unneeded data type `Gregorian` and rewrite stub.
Related to #211 and #302.
=> hspec-lens-person: Rewrite test to use hspec with fail-fast.

exercises/zipper/package.yaml, exercises/zipper/src/Zipper.hs, exercises/zipper/test/Tests.hs
- Rewrite test to use `hspec` with fail-fast.
- Remove comments from stub solution.
Related to #211 and #302.
=> zipper: Rewrite tests to use hspec with fail-fast.

.travis.yml, README.md
- Add hlint tests to the entire repository.
- Add and fix comments to match that.
It was briefly discussed in #355 that it would be interesting to run `HLint` in Travis-CI.
Thanks to @petertseng, we discovered that `hlint` is already available and whitelisted in Travis, but the version available in Ubuntu Precise is older than the ones we would like to run.
Initial experiments showed us that, installing it from source, the initial building times could be problematic. Another problem would be to assure that we are running a known version of HLint.
I opened this PR as an experiment, to see - after we finish #355 - if it is feasible to install and run it in "production". It also serves to check if we are really done with fixing the current code base.
The general idea is to …
=> travis: Add hlint to Travis-CI checks

README.md
Removes brackets accidentally inserted in `README.md` by #374.
=> documentation: Remove brackets from README.md

exercises/forth/package.yaml, exercises/forth/test/Tests.hs
- ~~~Move hint from test suite to `HINTS.md`.~~~
=> forth: Rewrite tests to use hspec with fail-fast.

exercises/crypto-square/src/CryptoSquare.hs, exercises/crypto-square/src/Example.hs, exercises/crypto-square/test/Tests.hs
This is a first draft of a new test suite based on what is being discussed in #259.
This diverges completely from `x-common`.
The test cases here are just examples of what needs to be tested, but the texts should probably be changed.
=> crypto-square: Completely rewrite tests.

exercises/leap/HINTS.md, exercises/leap/src/LeapYear.hs
This is an introductory exercise, so I think we should make things easier for the students. Most newcomers are still struggling to understand Haskell's type system and a signature can help a lot. 
The `HINTS.md` was added just to give the idea that the provided signature is not the only possible one.
I know that some people will disagree about it, saying that finding the type signatures is part of the problem, but if we make it too hard, a lot of people will give up. The ability to understand the types and the test suites will come with practice.
I believe that, as a rule, we should provide stub solutions with type signatures that allow compiling and running the tests whenever possible. Some exercises do not allow that - because that is the main challenge - and the students will have the …
=> leap: Add type signature and HINTS.md.

exercises/anagram/HINTS.md, exercises/anagram/package.yaml, exercises/anagram/src/Example.hs, exercises/anagram/test/Tests.hs
For a while, we are doings things that seem to increase the number of solutions accepted by the test suites:
- In #144 we fixed some exercises to allow polymorphic solutions to compile without warnings.
- In #211, we rewrote most of the test suites. In the process, some of the tests were changed to allow more general numeric types.
- In #391, we changed `crypto-square` to stop testing for intermediary functions, and test only for the essential properties of the solution.
- In #392, we recently agreed that we should ignore the order of the words returned by `anagramsFor`, because the order *is not an essential part of the problem*.
All of those things where based on the same idea: **To allow more diverse solutions**.
This seems to be aligned to what was discussed in exercism/discussions#41 …
=> anagram: Make the test suite as flexible as possible

config.json, exercises/zebra-puzzle/package.yaml, exercises/zebra-puzzle/src/Example.hs, exercises/zebra-puzzle/src/ZebraPuzzle.hs, exercises/zebra-puzzle/stack.yaml, exercises/zebra-puzzle/test/Tests.hs
The `Tests.hs` are pretty degenerated as they consist of just one test. So they could be simplified, but I did not want to interfere with the usual format.
And of course the position of the exercise in `config.json` can be changed. This is just some more or less arbitrary guess of mine.
There is this [Logic programming example](https://wiki.haskell.org/Logic_programming_example). I tried to be somewhat close to this one with my `Example.hs`. So we could consider to add this link as a hint.
=> new exercise zebra-puzzle

config.json
As part of the work in #274.
---
To discuss: Are all these difficulties right for us? I got lazy sometimes and looked at what difficulties F# track assigned them, since they are also functional and have all exercises except lens-person. there are some notable exceptions
* bank-account is significantly higher for us since we use IO monad for it
* our `robot-name` is significantly higher - we use IO monad
* our `nth-prime` may be lower since we can be lazy
* our accumulate/strain may be higher since we require laziness
* our `clock` is higher - it introduces a typeclass
Should we strictly order the exercises by difficulty, or is there sometimes a situation where we want to send a harder problem before an eaiser?
=> config.json: Assign and order problems by difficulty

exercises/leap/src/LeapYear.hs
Considering that `leap` is the first exercise of the track, this small change may help a beginner, because (he|she) may think that the part before `=` should not be changed.
More experienced students will certainly already know that they can eta-reduce the functions, so I think there is no harm.
To make the exercises more accessible to newcomers, I believe it is in general a good think to have a stub solution that:
- Includes the simplest type signature acceptable by the test suite.
- Includes a [eta-abstracted](https://wiki.haskell.org/Eta_conversion) fake implementation with reasonable variable names. I have been using `undefined` as the function body.
- Compiles and fails the tests, if possible without ruining the challenge.
What do you think about it, @petertseng?
=> leap: Add variable to stub solution's signature.

exercises/word-count/HINTS.md, exercises/word-count/examples/success-newtype/WordCount.hs, exercises/word-count/examples/success-newtype/package.yaml, exercises/word-count/examples/success-simple/WordCount.hs, exercises/word-count/examples/success-simple/package.yaml, exercises/word-count/src/Example.hs, exercises/word-count/src/WordCount.hs, exercises/word-count/test/Tests.hs
- Generalize the test suite to accept multiple signatures.
- Change the test suite to be case insensitive.
- Add `HINTS.md` explaining that the test suite is flexible.
- Add two example solutions: one very simple; the other with a custom type.
- Add the simplest type signature to the stub solution.
- Remove unneeded dependencies from `package.yaml`.
- Remove old example solution.
These changes tries to make this exercise, at the same time, more accessible and deeper. Beginners will probably be able to solve it easily, while more advanced students will be able the craft more elaborated solutions.
Also, we used `shouldMatchList` to improve error reporting and we normalize case before comparing, because the output's case *is not an essential part of the problem*.
This PR is very similar to …
=> word-count: Generalize test suite.

.travis.yml
PR #396 gives us the power to have multiple examples. But if the
examples have different dependencies, their caches clobber each other.
Thus, it seems necessary to have a separate cache per example.
There is some discussion on this and some proposed solutions in #397.
We may replace this shell script soon, but it will at least let us know
the strategy we want to use and validate the directory layout.
=> travis: Cache examples separately

exercises/space-age/HINTS.md
This is the first exercise in the track that fails compilation with the stub solution. We didn't had a complaint about it, but it may by a good idea to add a paragraph in `HINTS.md` explaining that it will not compile unless `Planet` is correctly implemented.
Should we do it?
=> space-age: Add warning about tests not compiling.

exercises/forth/test/Tests.hs
First commit is same as #412, the rest should bring us to match https://github.com/exercism/x-common/pull/394
=> forth: Add new tests from x-common

exercises/say/test/Tests.hs
Added in https://github.com/exercism/x-common/pull/399
Note that there is one place where we deviate:
We do not have an upper bound test.
This was discussed and decided in #292.
This deviation has been explicitly noted.
=> say: Declare compliance with x-common

exercises/grains/test/Tests.hs
Added in https://github.com/exercism/x-common/pull/420
We already match all cases.
=> grains: Declare compliance with x-common

config.json, exercises/alphametics/HINTS.md, exercises/alphametics/package.yaml, exercises/alphametics/src/Alphametics.hs, exercises/alphametics/src/Example.hs, exercises/alphametics/stack.yaml, exercises/alphametics/test/Tests.hs
of course feel free to change the place of the exercise in `config.json`. First I thought it makes sense to have it after `sgf-parsing` but then I saw its difficulty of 9 and reconsidered.
I kept the tests for multiplication and exponentiation from a former version of `canconical-data.json` as they make the exercise more interesting.
what annoys me is the more than 30 times worse performance than my same (I think) Scala implementation. would be very much interested to know the reason why.
=> new exercise alphametics

.travis.yml
=> travis: Use shorter paths for Stack's cache.

exercises/alphametics/package.yaml, exercises/atbash-cipher/package.yaml, exercises/bank-account/package.yaml, exercises/connect/package.yaml, exercises/crypto-square/package.yaml, exercises/food-chain/package.yaml, exercises/go-counting/package.yaml, exercises/grade-school/package.yaml, exercises/kindergarten-garden/package.yaml, exercises/largest-series-product/package.yaml, exercises/lens-person/package.yaml, exercises/linked-list/package.yaml, exercises/ocr-numbers/package.yaml, exercises/parallel-letter-frequency/package.yaml, exercises/rna-transcription/package.yaml, exercises/robot-name/package.yaml, exercises/saddle-points/package.yaml, exercises/say/package.yaml, exercises/scrabble-score/package.yaml, exercises/sgf-parsing/package.yaml, exercises/sieve/package.yaml, exercises/simple-cipher/package.yaml, exercises/triangle/package.yaml, exercises/wordy/package.yaml
=> Remove stub dependencies

config.json, exercises/word-count/examples/success-newtype/src/WordCount.hs, exercises/word-count/examples/success-simple/src/WordCount.hs, exercises/word-count/test/Tests.hs
Added in https://github.com/exercism/x-common/pull/403
---
discussion before merging:
These new tests seem to raise difficulty slightly because now we need to be sensitive to the difference between `'` as an apostrophe versus used as single quotes. I expect the example solution to need fixing, and I might bump the difficulty to 5 based on what I see.
=> word-count: Add more tests with punctuation

exercises/custom-set/HINTS.md, exercises/custom-set/src/CustomSet.hs
This PR makes small changes to allow the stub solution to build and also compile the test suite.
The ability to run the tests with the stub solution is useful mainly for two reasons:
- It allows us to assert that the stub solution is "correct".
- It allows the students to have an easier start, also making it clear what needs to be implemented.
On the other hand, it has drawbacks:
- We are forced to create a dummy data definition, which makes the exercise a little less challenging.
- We cannot export the data constructors to the test suite, because they do not exist yet.
Considering that most of the students don't go too far in the track, I'm not too worried about the risk of making it too easy, so I think it is worthy to try this path.
Related to #421.
=> custom-set: change stub to make it compile.

exercises/forth/HINTS.md, exercises/forth/src/Forth.hs
=> forth: Change stub to be able to run the tests.

exercises/series/HINTS.md, exercises/series/examples/success-byteseqs/package.yaml, exercises/series/examples/success-byteseqs/src/Series.hs, exercises/series/src/Series.hs, exercises/series/test/Tests.hs
- Change the test suite to accept multiple signatures.
- Add HINTS.md explaining how to work the exercise.
- Add a example solution using ByteStrings and Sequences.
- Add type signature to the stub solution.
- Add variables to the stub implementation.
These change also have the effect of allowing to run the test suite with the stub solution.
Related to #421.
=> series: rewrite to be flexible and improve stub.

exercises/grains/src/Grains.hs
Since we changed `grains` to expect a `Maybe` in https://github.com/exercism/xhaskell/pull/197, we had two users that opened issues about not being able to compile it: https://github.com/exercism/xhaskell/issues/305 and https://github.com/exercism/xhaskell/issues/430
The test suite seems correct, but users have a hard time trying to infer the correct types based on test suite.
This PR just add the expected type signatures to the stub solution.
=> grains: add signatures to stub solution

config.json, exercises/dominoes/examples/success-standard/package.yaml, exercises/dominoes/examples/success-standard/src/Dominoes.hs, exercises/dominoes/package.yaml, exercises/dominoes/src/Dominoes.hs, exercises/dominoes/stack.yaml, exercises/dominoes/test/Tests.hs
Just like our song-writing exercuses (beer-song, food-chain, house),
this one has to make heavy use of property-based tests since the number
of possible answers for even a small input can be very large.
=> add dominoes exercise

exercises/list-ops/test/Tests.hs
Currently the list-ops exercise's test case neither hides `filter` from `Prelude` nor does it import that function from the exercise code. Hence the test cases don't test the users implementation but the Prelude one's ...
=> list-ops: import/test filter function of exercise code

.travis.yml
- Fix small grammar error.
- Move calculation of exercise's name to outer loop.
- Build examples in separated folders
Creating distinct folders to build each one of the examples, we can be more confident that all tests are really independent.
Considering that we use distinct `.stack-work` directories, the only possible contamination seems to be the global Stack's cache. Now, with distinct paths for each example, it seems improbable that this will be a problem.
=> travis: build examples in separate folders and other small fixes

exercises/bowling/HINTS.md, exercises/bowling/examples/success-standard/src/Bowling.hs, exercises/bowling/src/Bowling.hs, exercises/bowling/test/Tests.hs
Changes as discussed in issue #440 .
I found it difficult to rephrase `HINTS.md`. It assumes the current `Requirements` of x-common's `description.md`. Any improvements here are especially welcome.
The example changes are based on the earlier version. So it might not be overly elegant.
=> integrated score function

.travis.yml, common/stack.yaml, config.json, exercises/pov/stack.yaml
As discussed in #442, it would be nice to have a single `stack.yaml` file and link all the others to it.
We expect this approach will work, but it is better to test fetching an exercise before making huge changes.
This PR does the following:
- Add `common/stack.yaml`
- Add `common` to ignore section in `config.json`
- Fix `.travis.yml` to dereference links when copying files for testing
- Symbolic link `stack.yaml` from exercism `pov`
Related to #442.
=> common: Add `stack.yaml` to common files folder and link `pov` as a test.

exercises/robot-name/examples/success-standard/src/Robot.hs
Patch example solution to fix the warning:
```
./exercises/robot-name/examples/success-standard/src/Robot.hs:7:1: Suggestion: Use newtype instead of data
Found:
data Robot = Robot{robotNameVar :: MVar String}
Why not:
newtype Robot = Robot{robotNameVar :: MVar String}
Note: decreases laziness
1 hint (5 ignored)
```
The `nightly` snapshot currently fails the tests in Travis-CI because of that warning.
=> robot-name: Fix hlint-1.9.38 newtype warning

exercises/difference-of-squares/test/Tests.hs
The test `huge difference` has caused some difficulties
to users because the most common solutions use the `sum`
function, that seems to be implemented as a `foldr`.
A naive implementation would certainly fail the test or,
in the worst case scenario, allocate all the memory and
crash the operating system.
Closes #449.
=> difference-of-square: Comment out last test

exercises/pov/stack.yaml
The experiment proposed in #442 of symbolic linking the
`stack.yaml` file has failed, as the file was not fetched
as expected.
This PR partially reverts #443, but leaves the fix
in `.travis.yml` and the `common/stack.yaml` file.
=> pov: Revert linking `common/stack.yaml`

exercises/pov/.dummylink
In #442 we conjectured that using symbolic links to a common `stack.yaml` would be feasible, but the test (#443) didn't work as expected. 
The result of the experiment was a `pov` exercise without a `stack.yaml` file, and #453 was opened on fix that.
To keep testing symbolic links, we still need to use `pov` as a test bed, but this time without breaking it, so we use another symbolic link name, unrelated to the exercise.
=> pov: Add dummy symbolic link

README.md
this is the respective first draft for issue #448 to start the review.
Is it too much marketing speak? Shall we be more straight to the point?
I think it is also becoming too big. Perhaps better have just some shorter and more general info (more like a verbose TOC) with links to the various subtopics as separate `.md` files?
=> Add more contributor information to README.md

SETUP.md
In #462, we moved it to TRACK_HINTS.md
HOWEVER, we are the very first track to do so, so the code is untested.
It is possible something can go wrong.
If we want to be paranoid, we can add a SETUP.md so that if TRACK_HINTS
fails we don't leave our students in the dark.
This SETUP.md is slightly different from TRACK_HINTS.md: It has only one
space after the period on the last line, rather than two.
This way, we can tell which of the two files is being used.
---
Note to reviewers: We *do not necessarily* need to merge this. This all depends on how paranoid we are feeling. I have confidence in https://github.com/exercism/trackler/blob/master/lib/trackler/implementation.rb#L105 that our TRACK_HINTS.md is in the right place, but it is possible to be paranoid, and delete the SETUP.md file once …
=> SETUP.md: Add for paranoia

exercises/grade-school/.meta/DONT-TEST-STUB, exercises/grade-school/HINTS.md, exercises/grade-school/src/School.hs
Lingering work from #421 and #464.
~~It seems acceptable to define the `Grade` and `Student` type synonyms in
the stub, so that the expected return types of the functions will all be
self-explanatory.~~
~~The alternative is, of course, not to define them, and replace all
instances of `Grade` with `Int` and `Student` with `String`, and let the
students figure it out on their own.~~
Although the example solution defines `Grade` and `Student` type
synonyms, we generally leave the definition of these type synonyms to
individual students, so the type signatures provided will just have
`Int` and `String`.
---
What say y'all? Should we define `Grade` and `Student`, or let the students do it? Do we have a precedent? I will say the only other `type` we ever define in a stub is `type Coord = (Int, …
=> grade-school: Add signatures to stub so it runs tests

exercises/allergies/.meta/DONT-TEST-STUB, exercises/allergies/src/Allergies.hs, exercises/meetup/.meta/DONT-TEST-STUB, exercises/meetup/HINTS.md, exercises/meetup/src/Meetup.hs, exercises/space-age/.meta/DONT-TEST-STUB, exercises/space-age/HINTS.md, exercises/space-age/src/SpaceAge.hs
This is the concrete proposal to go along with #466.
If y'all think #466 is a good idea, then this is the way to go.
Closes #466.
=> allergies, space-age, meetup-day; Fully define data in stub

exercises/lens-person/examples/success-standard/package.yaml, exercises/lens-person/examples/success-standard/src/Person.hs
Here is a proposal.
`lens` is quite a large library with many dependencies, right? And it is not strictly required to pass the tests of the `lens-person` exercise.
So, what if we were to reduce our dependency footprint by not using `lens` at all?
I'm not sure whether this will actually have a noticeable benefit for us and/or whether using `lens` is actually causing us any problems. Let's see.
=> lens-person: Remove lens from example solution

config.json
While evaluating that a proposed hello-world exercise in #475 would
introduce Maybe into the track at the first exercise, I found myself
wondering what other exercises introduce Maybe. I decided to put this,
and select other topics, into the config.json file.
The topics selected are, largely, those that might affect a problem
ordering decision. They are topics that either require some effort to
grasp (so we should not put them too early) and/or are repetitive (so we
should not place them too close together).
* Maybe
* Either
* Lazy evaluation
* Define a data type
* Library reimplementation
* Refactoring
* accumulator-strictness
* instance TC (where TC is any typeclass other than Eq or Show)
* IO Monad
* Random
* Mutable state
Closes #274.
=> config.json: Add select topics

exercises/phone-number/examples/success-standard/src/Phone.hs, exercises/phone-number/src/Phone.hs, exercises/phone-number/test/Tests.hs
areaCode and prettyPrint are hereby removed.
https://github.com/exercism/x-common/pull/477
---
Reviewers: many cases were changed as a result of syncing to x-common. Are there any cases in particular you wish to keep?
In particular, note that all `Just` results are `1234567890`. If you wish for more variety, please speak up.
=> phone-number: simplify to number only

config.json, exercises/secret-handshake/.meta/DONT-TEST-STUB, exercises/secret-handshake/HINTS.md, exercises/secret-handshake/examples/success-standard/src/SecretHandshake.hs, exercises/secret-handshake/src/SecretHandshake.hs, exercises/secret-handshake/test/Tests.hs
This removes the string cases; the function-under-test is now only
obligated to accept integers.
Note that the now-deleted HINTS.md accepted that this API design was
bad, so it is good to get rid of it.
---
Reviewers: this is a bit of a shame, as we are getting rid of a unique request of students (to make a function take both a string and a number). But I also think that this problem might be a bit too early to make this request. Do you want to keep it and/or revive this concept in another problem?
The only other problem in which we request students to implement a typeclass is in Clock.
=> secret-handshake: use cases from x-common

exercises/nucleotide-count/examples/success-standard/src/DNA.hs, exercises/nucleotide-count/src/DNA.hs, exercises/nucleotide-count/test/Tests.hs
It was decided that the exercise was doing too many things, and count
really is just one element of nucleotideCounts anyway.
https://github.com/exercism/x-common/pull/505
=> nucleotide-count: simplify to only nucleotideCounts

exercises/prime-factors/test/Tests.hs
https://github.com/exercism/x-common/pull/513
---
reviewers: your opinion will be appreciated on whether to incorporate the test descriptions into the file.
1. Do nothing.
2. Include as comments.
3. Include as an element of the tuple, then use `it` on them so thye become test descriptions.
=> prime-factors: use cases of x-common

config.json, exercises/hello-world/HINTS.md, exercises/hello-world/examples/success-standard/package.yaml, exercises/hello-world/examples/success-standard/src/HelloWorld.hs, exercises/hello-world/package.yaml, exercises/hello-world/src/HelloWorld.hs, exercises/hello-world/stack.yaml, exercises/hello-world/test/Tests.hs
This PR adds the `hello-world` exercise, as requested in https://github.com/exercism/todo/issues/34.
This is my first PR in this language track, so I hope everything is in order. Let me know if it isn't.
=> Add hello-world exercise

exercises/allergies/src/Allergies.hs, exercises/atbash-cipher/src/Atbash.hs, exercises/bank-account/src/BankAccount.hs, exercises/binary-search-tree/src/BST.hs, exercises/bowling/src/Bowling.hs, exercises/clock/src/Clock.hs, exercises/connect/src/Connect.hs, exercises/crypto-square/src/CryptoSquare.hs, exercises/custom-set/src/CustomSet.hs, exercises/difference-of-squares/src/Squares.hs, exercises/etl/src/ETL.hs, exercises/forth/src/Forth.hs, exercises/go-counting/src/Counting.hs, exercises/kindergarten-garden/src/Garden.hs, exercises/largest-series-product/src/Series.hs, exercises/lens-person/src/Person.hs
Part of #473 
Perhaps the next PRs will be smaller, so they can be reviewed easier.
I was thinking about some of the exercises covered in this PR and how much more complex they are in comparison to the first 10 - 15 available exercises (the ones I've completed so far).
Once the student get there, he will have crossed a few Haskell / FP concepts, which is one of the goals of this Track.
Consequently, wouldn't [eta-conversion](https://wiki.haskell.org/Eta_conversion) also be part of the concepts he should familiarize with? Therefore, I believe that, starting from a complex enough exercise, keeping the function arguments out would create a better learning experience.
=> Add explicit args to Exercises - Part 1

exercises/pov/src/POV.hs, exercises/pythagorean-triplet/src/Triplet.hs, exercises/queen-attack/src/Queens.hs, exercises/raindrops/src/Raindrops.hs, exercises/robot-name/src/Robot.hs, exercises/robot-simulator/src/Robot.hs, exercises/roman-numerals/src/Roman.hs, exercises/run-length-encoding/src/RunLength.hs, exercises/saddle-points/src/Matrix.hs, exercises/say/src/Say.hs, exercises/scrabble-score/src/Scrabble.hs, exercises/secret-handshake/src/SecretHandshake.hs, exercises/sgf-parsing/src/Sgf.hs
Part of #473 
The [POV](http://exercism.io/exercises/haskell/pov/readme) page is broken. I can open an Issue if that's the case.
=> Add Explicit Args To Exercises - Part 3

exercises/simple-linked-list/examples/success-standard/package.yaml, exercises/simple-linked-list/examples/success-standard/src/LinkedList.hs, exercises/simple-linked-list/package.yaml, exercises/simple-linked-list/src/LinkedList.hs, exercises/simple-linked-list/test/Tests.hs
#498 Property-based Testing
This is just to have some concrete code for discussion.
I simply used the existing QuickCheck tests from `octal` and `trinary` to get started.
One immediate problem is the compiler warning about the orphanned instance declaration. Is there some easy way to solve this?
=> simple-linked-list: Add QuickCheck tests

common/stack.yaml, config.json, exercises/pov/.dummylink
Closes #442 
Details in individual commit messages.
Let me merge this one since it has a "Closes exercism/trackler#13" in it and I'm the issue creator so it'll only work if I merge it.
=> Revert "pov: Add dummy symbolic link (#454)" and "common: Add folder with common exercise's files"

config.json, exercises/pangram/examples/success-standard/package.yaml, exercises/pangram/examples/success-standard/src/Pangram.hs, exercises/pangram/package.yaml, exercises/pangram/src/Pangram.hs, exercises/pangram/stack.yaml, exercises/pangram/test/Tests.hs
I think this exercise is fairly trivial to be implemented. Plus, it is good to have more exercises between Bob and Run Length Encoding, since the first is much simpler than the latter.
=> Add Pangram Exercise

config.json, exercises/bracket-push/examples/success-standard/package.yaml, exercises/bracket-push/examples/success-standard/src/Brackets.hs, exercises/bracket-push/package.yaml, exercises/bracket-push/src/Brackets.hs, exercises/bracket-push/stack.yaml, exercises/bracket-push/test/Tests.hs
Port [Bracket Push][1] to the Haskell Track.
For the [Example Solution][2], I tried to explore Data constructors and the Maybe type.
[1]: https://github.com/exercism/x-common/tree/master/exercises/bracket-push
[2]: https://github.com/lpalma/xhaskell/blob/94ea00b9a6823a332772436ed6a8a723a30efaef/exercises/bracket-push/examples/success-standard/src/BracketPush.hs
=> Add Bracket Push Exercise

config.json, exercises/acronym/examples/success-standard/package.yaml, exercises/acronym/examples/success-standard/src/Acronym.hs, exercises/acronym/package.yaml, exercises/acronym/src/Acronym.hs, exercises/acronym/stack.yaml, exercises/acronym/test/Tests.hs
Port [Acronym](https://github.com/exercism/x-common/tree/master/exercises/acronym) to the Haskell Track.
As always, happy to receive feedback :-)
=> Add Acronym Exercise

exercises/kindergarten-garden/package.yaml, exercises/kindergarten-garden/test/Tests.hs
Descriptions are clearer as to the significance of the garden size, or
the fact that the given student list is non-alphabetical.
The tests of the middle children in the full garden are elided.
The canonical data file was added in https://github.com/exercism/x-common/pull/770
=> kindergarten-garden 1.0.0.2: edit descriptions and elide middle students

exercises/bowling/package.yaml, exercises/bowling/test/Tests.hs
We were mostly already compliant.
https://github.com/exercism/x-common/pull/536
https://github.com/exercism/x-common/pull/536/commits/58ef1d28174df767e929e52592af372a91864cbb
=> bowling 1.0.0.2: drop unneeded rolls, edit a description

exercises/luhn/examples/success-standard/src/Luhn.hs, exercises/luhn/package.yaml, exercises/luhn/src/Luhn.hs, exercises/luhn/test/Tests.hs
https://github.com/exercism/x-common/pull/474
https://github.com/exercism/x-common/pull/496
https://github.com/exercism/x-common/pull/522
https://github.com/exercism/x-common/pull/547
In consideration of https://github.com/exercism/x-common/issues/523, we
will not be testing the invalid inputs. They have been commented out.
Closes #469
=> luhn 1.0.0.2: only test isValid, use (most) x-common cases

exercises/phone-number/examples/success-standard/src/Phone.hs, exercises/phone-number/package.yaml, exercises/phone-number/test/Tests.hs
1.0.1 and 1.0.2: description clarifications
https://github.com/exercism/x-common/pull/719
https://github.com/exercism/x-common/pull/724
1.1.0: enforce area/exchange not starting with 1
https://github.com/exercism/x-common/pull/745
1.2.0: 1a2b3c4d5e6f7g8h9i0j removed
https://github.com/exercism/x-common/pull/772
Closes #518
=> phone-number 1.2.0.3: enforce area/exchange not starting with 1

exercises/roman-numerals/package.yaml, exercises/roman-numerals/test/Tests.hs
https://github.com/exercism/x-common/pull/707
=> roman-numerals 1.0.0.2: add descriptions

exercises/dominoes/package.yaml, exercises/dominoes/test/Tests.hs
There have always been nine elements, ever since the origin of this test
in https://github.com/exercism/xrust/pull/13#discussion_r115148635
The description incorrectly claimed ten.
https://github.com/exercism/x-common/pull/777
=> dominoes 1.0.1.3: correctly declare nine elements in largest case

exercises/pov/package.yaml, exercises/pov/test/Tests.hs
This was the main change in https://github.com/exercism/x-common/pull/704
https://github.com/exercism/x-common/pull/710 is an inconsequential
change that does not affect our tests.
Two other changes in 1.1.0 that aren't exactly followed:
* As a part of conforming to the canonical schema, trees were embedded
into the test data, but we have no need to do it - let's reduce
duplication, and besides we are safe from accidental mutation.
* The "cannot trace" cases were changed to use simpler trees than
cousins, but we would have had to introduce another tree to do that
(one with kids and siblings). We'll stick with cousins.
=> pov 1.1.1.3: simplify "Can find path from nodes other than x"

exercises/change/package.yaml, exercises/change/test/Tests.hs
Reference test data has no test groups, so we remove the unneeded two levels of nesting.
Note that the exercise's name is always automatically displayed when running the tests suite.
=> change: Remove test groups not matching x-common

exercises/pythagorean-triplet/.meta/DONT-TEST-STUB
Type signatures where added to the stub solution by #507, so we can test if everything compiles with it.
Closes #509.
ps: I know that this is a *good-first-patch* issue, but it is hanging there for too long...
=> pythagorean-triplet: Remove .meta/DONT-TEST-STUB

exercises/matrix/test/Tests.hs
~~It was argued in #541 that the the exercise would be more interesting without the `fromString` function, which is not an essential part of of it.~~
- ~~Rewrite test suite to use `[[Int]]` instead of `String`.~~
- ~~Remove test that wouldn't make sense without `fromString`.~~
- ~~Remove all other references to `fromString`.~~
- ~~Fix `HINTS.md` to remove reference to invalid characters.~~
---
**Edit**:
The scope of this PR was restricted to just removing the last three tests, based on the discussion below. If in the future we decided to completely remove `fromString` from the test suite, `description.md` will demand some rewriting.
I think that it is preferable to completely rewrite or remove this exercise. The way it is now is lacks focus and also exposes users to a really unidiomatic …
=> matrix: Remove string tests

exercises/difference-of-squares/package.yaml, exercises/difference-of-squares/test/Tests.hs
Tests for 10 are removed, tests for 1 are added, and the test for
`difference 0` was removed.
https://github.com/exercism/x-common/pull/791
=> difference-of-squares 1.1.0.4: Test 1, 5, 100 for all functions

.travis.yml
- Raise cache upload timeout from 180 to 600.
As the Travis-CI tests gets more complex, the amount of cache needed to rebuild it efficiently also increases. Now we reached a situation where it is sometimes too big to be uploaded in time.
```
uploading archive
running `casher push` took longer than 180 seconds and has been aborted
Done. Your build exited with 0.
```
While this doesn't fail the tests, it makes reviewing PRs painfully slow.
=> travis: Increase cache upload timeout

bin/test-example
Exercise's examples that are always expected to fail the building step are rebuilt by Stack everytime. This triggers a cache update in Travis-CI, even when nothing changed in the repository.
While this problem doesn't affect pull requests that already change the cache, it slows down the all the other PRs by sometimes around 3 minutes.
Removing the cache folder for error-type examples, we expect to have clean rebuilds in Travis.
Closes #544.
=> travis: Remove error-type examples's cache

bin/test-example, bin/test-stub
- Enable building benchmarks when testing the exercises.
While it is undesirable to run benchmarks as part of the tests, checking that the stubs and example solutions can compile with them is needed to assure that the user will be able to run the benchmarks.
=> travis: Build exercise's benchmarks

bin/test-example, bin/test-stub
To address @petertseng's concern: 😁 
> It's a shame that we'll no longer error on the cp if, say, a stack.yaml is missing, but I guess it's OK that the error happens later.
Sorry for not fixing that in #552.
=> test-scripts: Fix benchmark folder copy

exercises/parallel-letter-frequency/HINTS.md, exercises/parallel-letter-frequency/bench/Benchmark.hs, exercises/parallel-letter-frequency/examples/success-standard/package.yaml, exercises/parallel-letter-frequency/package.yaml
Fixes https://github.com/exercism/xhaskell/issues/519
I've added a benchmark test that makes sure that `frequency` function runs at least 10% faster (arbitrary number) with multiple workers that with a single worker.
It increases the time it takes to run the tests by about 5 seconds on my machine, not sure if it's acceptable. It might be possible to make it faster by tweaking Criterion settings.
Another concern is the benchmark test would only work correctly on a machine with at least 2 cores.
It prints the benchmark results into the console:
```
frequency
no texts mean no letters
one letter
case insensitivity
many empty texts still mean no letters
many times the same text gives a predictable result
punctuation doesn't count
numbers don't count
all three anthems, together, 1 worker
all …
```
=> parallel-letter-frequency: Add benchmark

.gitignore, README.md, config.json, docs/EXERCISE_README_INSERT.md
The leading 'x' is kind of arbitrary. Especially now that we can set
topics on the repositories, we don't need a pattern to distinguish what
is a track or not.
The repository itself has already been renamed. GitHub redirects from
the old name to the new name, so we do not have to rush to fix links to
the old repository name, though we should update them for the sake of
clarity.
See exercism/meta#1
=> Remove leading 'x' from repository name

config.json, exercises/spiral-matrix/examples/success-standard/package.yaml, exercises/spiral-matrix/examples/success-standard/src/Spiral.hs, exercises/spiral-matrix/package.yaml, exercises/spiral-matrix/src/Spiral.hs, exercises/spiral-matrix/stack.yaml, exercises/spiral-matrix/test/Tests.hs
This is the implementation of the exercise as initially proposed in exercism/x-common#840.
I'm not sure about the difficulty, so I inserted it just after `food-chain`, for contrast.
~~We shouldn't merge this before `x-common`, as this exercises references the `1.0.0` version of the test cases. I'm just opening this PR so that we can have fix major problems beforehand.~~
=> spiral-matrix: Add exercise

exercises/pangram/package.yaml, exercises/pangram/test/Tests.hs
From what I can see, the last test case is inteded to catch incorrect
programs such as this, which don't take into account different-cased
duplicates:
```haskell
isPangram = (== 26) . length . nub . filter isAlpha
```
However the above program passed the final test as the count of distinct
upper and lower case characters is 27, rather than 26.
This commit changes the test text to a non-pangram that has exactly 26
distinct upper and lower case characters, which causes the above,
incorrect program to fail.
=> fix pangram test for duplicate mixed-case chars

exercises/simple-linked-list/test/Tests.hs
This exercise has the only test suite in the repository that does an unqualified import of a module from an external library without an explicit import list.
This style of importing in not recommended:
- https://wiki.haskell.org/Import_modules_properly
Besides that, it is nice to keep consistency when it is cheap to do it.
=> simple-linked-list: Make library import explicit

bin/test-example, bin/test-stub
Travis timeouts jobs after 50 minutes, and we are having problems trying to stay under this limit when building initially with an empty cache.
To save some precious minutes, we are temporarily disabling compilation of the benchmarks suites, because 'criterion' is a really heavy dependency.
Related to #568.
=> travis: Disable building the benchmarks

config/maintainers.json
As suggested in #581.
@petertseng wrote:
> Probably makes sense to say that etrepum is alumnus.
@kytrinyx wrote:
Probably. If he doesn't pop in here I'll send him an email to see if he's OK with that.
=> maintainers: Set etrepum as alumnus

config/maintainers.json
Without a `bio`, only my GitHub username would be displayed, so I wrote a Haskell-specific *"[In a world...](http://tvtropes.org/pmwiki/pmwiki.php/Main/InAWorld)"* one, inspired by [this trailer](https://www.youtube.com/watch?v=fVDzuT0fXro).
=> maintainers: Show rbasso on website

config.json
The default example pattern matches more than just the reference solution.
It also matches some of the support files that live within the example directories, such
as yaml files.
This has been tested against configlet to ensure that it detects a reference solution
for each exercise.
=> Add an explicit example pattern to the track config

config.json, exercises/isogram/README.md, exercises/isogram/examples/success-standard/package.yaml, exercises/isogram/examples/success-standard/src/Isogram.hs, exercises/isogram/package.yaml, exercises/isogram/src/Isogram.hs, exercises/isogram/stack.yaml, exercises/isogram/test/Tests.hs
Another Unimplemented exercise
=> adding isogram

exercises/leap/package.yaml, exercises/leap/test/Tests.hs
Currently, the test suite has a loophole where it is possible to pass
all the tests with a function that simply checks if year \`mod\` 16 == 0.
This commit changes one of the test cases so that is no longer possible.
=> leap: Improve test suite to cover corner case.

config.json
Compare:
ruby -rjson -e 'puts JSON.parse(File.read("config.json"))["exercises"].select { |e| e["topics"]&.include?("Define type") }.map { |e| e["slug"] }' | sort
git grep Dummy
=> config.json: add "Define type" to complex-number

exercises/alphametics/examples/success-standard/src/Alphametics.hs, exercises/wordy/examples/success-standard/src/WordProblem.hs
This is suggested by a newer version of hlint, so Travis CI had pointed
this out for the builds that use nightly Stackage.
2.0.9 is known not to emit the suggestion in question, and 2.0.10 is
known to do so.
=> alphametics, wordy: Use $> instead of *> pure

exercises/forth/package.yaml, exercises/forth/test/Tests.hs
https://github.com/exercism/problem-specifications/pull/976
It is not necessary to verify that the implementation matches the
specification, since the specification does not define behaviour of
empty inputs.
=> forth 1.3.0.5: rm test of empty input

config.json, exercises/rail-fence-cipher/README.md, exercises/rail-fence-cipher/examples/success-standard/package.yaml, exercises/rail-fence-cipher/examples/success-standard/src/RailFenceCipher.hs, exercises/rail-fence-cipher/package.yaml, exercises/rail-fence-cipher/src/RailFenceCipher.hs, exercises/rail-fence-cipher/stack.yaml, exercises/rail-fence-cipher/test/Tests.hs
I'm not sure about the types on ```src/RailFenceCipher.hs```
Should I change them to ``` f :: Int -> String -> String``` or change the ones from the tests?
=> Implementing rail-fence-cipher

exercises/bob/README.md, exercises/bob/examples/success-standard/src/Bob.hs, exercises/bob/package.yaml, exercises/bob/test/Tests.hs
Closes https://github.com/exercism/problem-specifications/issues/943.
It was possible for a message directed to Bob to be both a question and
yelling, which meant it was unclear which rule should take effect.
Resolve ambiguity by simply adding a rule for that case.
https://github.com/exercism/problem-specifications/pull/1025
=> bob 1.1.0.4: Add yelling question rule

docs/LEARNING.md, exercises/food-chain/examples/success-standard/src/FoodChain.hs, exercises/forth/examples/success-standard/src/Forth.hs, exercises/parallel-letter-frequency/examples/success-standard/src/Frequency.hs, exercises/sgf-parsing/examples/success-standard/src/Sgf.hs, exercises/zipper/examples/success-standard/src/Zipper.hs
Now `git grep '  *$'` only has some README files where the
problem-specifications files contain trailing whitespace. So this is
good.
TBD: Should this be checked via CI?
=> remove trailing whitespace

exercises/acronym/package.yaml, exercises/all-your-base/package.yaml, exercises/all-your-base/test/Tests.hs, exercises/allergies/package.yaml, exercises/anagram/package.yaml, exercises/atbash-cipher/package.yaml, exercises/bob/package.yaml, exercises/bracket-push/package.yaml, exercises/change/package.yaml, exercises/collatz-conjecture/package.yaml, exercises/connect/package.yaml, exercises/crypto-square/package.yaml, exercises/diamond/package.yaml, exercises/difference-of-squares/package.yaml, exercises/dominoes/package.yaml, exercises/isbn-verifier/examples/success-standard/src/IsbnVerifier.hs, exercises/isbn-verifier/package.yaml, exercises/isbn-verifier/test/Tests.hs, exercises/luhn/package.yaml, exercises/luhn/test/Tests.hs, exercises/meetup/package.yaml, exercises/rail-fence-cipher/package.yaml, exercises/rna-transcription/package.yaml, exercises/rna-transcription/test/Tests.hs
Mostly no-ops
This script helps:
```ruby
require 'json'
pr = ARGV[0]
exercise = `pwd`.chomp.split(?/).last
ver = JSON.parse(File.read("../../../problem-specifications/exercises/#{exercise}/canonical-data.json"))['version']
haskell_ver = Integer(`grep version: package.yaml`.chomp[-1])
`sed -i'' -e "s/^version: .*/version: #{ver}.#{haskell_ver + 1}/" package.yaml`
m = "#{exercise}: #{ver}.#{haskell_ver + 1}: no-op declare compliance with #{ver}
input object
https://github.com/exercism/problem-specifications/pull/#{pr}"
`git commit --all -m '#{m}'`
puts m
```
Remaining to do: alphametics adds big test which I'll probably comment out for time? We'll see
list-ops just haven't gotten around to using the exact same tests
palindrome-products not using Maybe
=> match problem-specifications versions

exercises/hello-world/package.yaml, exercises/largest-series-product/package.yaml, exercises/leap/package.yaml, exercises/minesweeper/package.yaml, exercises/nth-prime/package.yaml, exercises/nucleotide-count/package.yaml, exercises/pascals-triangle/package.yaml, exercises/perfect-numbers/package.yaml, exercises/phone-number/package.yaml, exercises/phone-number/test/Tests.hs, exercises/pig-latin/package.yaml, exercises/rna-transcription/package.yaml, exercises/roman-numerals/package.yaml, exercises/rotational-cipher/package.yaml, exercises/saddle-points/package.yaml, exercises/scrabble-score/package.yaml, exercises/secret-handshake/package.yaml, exercises/sieve/package.yaml, exercises/space-age/package.yaml, exercises/spiral-matrix/package.yaml, exercises/sublist/package.yaml, exercises/twelve-days/package.yaml, exercises/zebra-puzzle/package.yaml
still using the same script
```ruby
require 'json'
pr = ARGV[0]
exercise = `pwd`.chomp.split(?/).last
ver = JSON.parse(File.read("../../../problem-specifications/exercises/#{exercise}/canonical-data.json"))['version']
haskell_ver = Integer(`grep version: package.yaml`.chomp[-1])
`sed -i'' -e "s/^version: .*/version: #{ver}.#{haskell_ver + 1}/" package.yaml`
m = "#{exercise}: #{ver}.#{haskell_ver + 1}: no-op declare compliance with #{ver}
input object
https://github.com/exercism/problem-specifications/pull/#{pr}"
`git commit --all -m '#{m}'`
puts m
```
=>  phone-number 1.4.0.5: Add cases for area code/exchange start with 1 (and accompanying no-ops)

config.json
Closes #639
* (collatz-conjecture stays where it is, 1)
* perfect-numbers 2
* isogram 2
* diamond 2
* (twelve-days stays where it is, 3)
* isbn-verifier 3
* run-length-encoding 3
* this is also helpful because it places two exercises between
twelve-days and beer-song, avoiding boredom from repeated
text-generation exercfise
* complex-numbers 3
* instructions are given, but there are many of them
* rotational-cipher 5
* rail-fence-cipher 6
I don't have justifications for many of these numbers; they're just
arbitrary feelings.
=> config.json: Reorder exercises

README.md
It's being renamed in https://github.com/exercism/haskell/pull/640
(Note changes to test and Tests.hs lines are just to extend the vertical
lines)
=> README: replace HINTS.md with .meta/hints.md

exercises/rna-transcription/README.md
This one I did manually (there were only two) but remember the procedures:
```
git format-patch $PREVIOUS_COMMIT -- exercises/*/description.md exercises/*/metadata.yml 
vim *.patch
git checkout -b readme $PREVIOUS_COMMIT
git am *.patch
git rebase -i $PREVIOUS_COMMIT
```
`../configlet/bin/generate . && git cal --date="$(git --git-dir=../problem-specifications/.git show --format=%ai -s HEAD)" --author="$(git --git-dir=../problem-specifications/.git show --format='%an <%ae>' -s HEAD)" -m "$(git --git-dir=../problem-specifications/.git log --format=%B -n1 HEAD)"`
our READMEs now match dae85658c4676c275dff5adee2ed0de109a38a9f
---
rna-transcription: provide more accurate source info
Original source seemed to mention a simple replacement of T with U
rather than the transcription being performed. …
=> rna-transcription: provide more accurate source info

exercises/rna-transcription/package.yaml, exercises/rna-transcription/test/Tests.hs
The return type of `Maybe String` already anticipates error handling, but I've seen many solutions on exercism.io that would just throw an exception on invalid input. This test should point people in the right direction.
=> rna-transcription: Add test case for invalid input

exercises/acronym/package.yaml, exercises/acronym/test/Tests.hs, exercises/anagram/package.yaml, exercises/anagram/test/Tests.hs, exercises/clock/package.yaml, exercises/clock/test/Tests.hs, exercises/complex-numbers/package.yaml, exercises/custom-set/package.yaml, exercises/hamming/package.yaml, exercises/kindergarten-garden/package.yaml, exercises/ocr-numbers/package.yaml, exercises/prime-factors/package.yaml, exercises/queen-attack/package.yaml, exercises/rail-fence-cipher/package.yaml, exercises/raindrops/package.yaml, exercises/robot-simulator/package.yaml, exercises/roman-numerals/package.yaml, exercises/roman-numerals/test/Tests.hs, exercises/run-length-encoding/package.yaml, exercises/word-count/package.yaml
still used same script
```ruby
require 'json'
pr = ARGV[0]
exercise = `pwd`.chomp.split(?/).last
ver = JSON.parse(File.read("../../../problem-specifications/exercises/#{exercise}/canonical-data.json"))['version']
haskell_ver = Integer(`grep version: package.yaml`.chomp[-1])
`sed -i'' -e "s/^version: .*/version: #{ver}.#{haskell_ver + 1}/" package.yaml`
m = "#{exercise}: #{ver}.#{haskell_ver + 1}: no-op declare compliance with #{ver}
input object
https://github.com/exercism/problem-specifications/pull/#{pr}"
`git commit --all -m '#{m}'`
puts m
```
=> match problem-specifications versions 

exercises/matrix/package.yaml, exercises/matrix/test/Tests.hs
https://github.com/exercism/problem-specifications/pull/1115
We will keep our track-specific tests since the presence of the
canonical-data.json does not give us a reason to remove them.
=> matrix 1.0.0.4: Use row/column tests from problem-specifications

exercises/matrix/package.yaml, exercises/matrix/test/Tests.hs
It might seem fair enough to have a space here. But the parsing is quite strict, for example expecting "" to parse to a matrix with 0 rows and 0 columns. So there really shouldn't be an extra space in a space-separated list of values.
=> Remove space from test string.

exercises/diamond/examples/success-standard/src/Diamond.hs, exercises/diamond/package.yaml, exercises/diamond/src/Diamond.hs, exercises/diamond/test/Tests.hs
Maybe the exercise will be changed by #600, but IMHO there is no need not to solve #626 now.
Closes #626.
=> diamond: Change return type to Maybe

config.json, exercises/protein-translation/README.md, exercises/protein-translation/examples/success-standard/package.yaml, exercises/protein-translation/examples/success-standard/src/ProteinTranslation.hs, exercises/protein-translation/package.yaml, exercises/protein-translation/src/ProteinTranslation.hs, exercises/protein-translation/stack.yaml, exercises/protein-translation/test/Tests.hs
I wanted to use  ```chunksOf``` from [Data.List.Split](https://hackage.haskell.org/package/split-0.2.3.2/docs/Data-List-Split.html#v:chunksOf) but apparently it is not in the cabal configuration
=> Implementing protein-translation

exercises/go-counting/README.md, exercises/go-counting/package.yaml, exercises/go-counting/test/Tests.hs
https://github.com/exercism/problem-specifications/pull/1195
=> go-counting 1.0.0.3: Match new canonical data

config.json, exercises/all-your-base/examples/success-standard/src/Base.hs, exercises/all-your-base/src/Base.hs, exercises/all-your-base/test/Tests.hs, exercises/largest-series-product/examples/success-standard/src/Series.hs, exercises/largest-series-product/src/Series.hs, exercises/largest-series-product/test/Tests.hs
Currently the only two exercises that expect specific errors are:
Bowling:
#441
Forth:
#14
It would be good to encourage the usage of programmatically inspectable
errors in other exercises that can fail in multiple ways.
=> all-your-base, largest-series-product: Expect specific errors

exercises/isbn-verifier/package.yaml, exercises/isbn-verifier/test/Tests.hs
Set new test case to be 3-598-P1581-X.
This will actually catch incorrect solutions - when invalid characters (P) are treated as 0.
3 * 10 + 5 * 9 + 9 * 8 + 8 * 7 + 0 * 6 + 1 * 5 + 5 * 4 + 8 * 3 + 1 * 2 + 10 * 1 = 264
264 is divisible by 11.
The previous case did NOT have this property:
3 * 10 + 5 * 9 + 9 * 8 + 8 * 7 + 2 * 6 + 0 * 5 + 5 * 4 + 0 * 3 + 7 * 2 + 0 * 1 = 249
249 is NOT divisible by 11.
https://github.com/exercism/problem-specifications/issues/1212
https://github.com/exercism/problem-specifications/pull/1217
=> isbn-verifier 2.3.0.4: Use an otherwise-valid ISBN in invalid char test

exercises/bracket-push/package.yaml, exercises/bracket-push/test/Tests.hs
Guards against solutions immediately declaring the entire string matched
as soon as they find any one matched pair.
https://github.com/exercism/problem-specifications/pull/1219
=> bracket-push 1.3.0: Add paired inside unpaired

.travis.yml
This will help diagnose any issues that may come up because of differing
stack versions and/or compiled packages.
=> travis: Display stack version

exercises/series/README.md, exercises/series/examples/success-byteseqs/src/Series.hs, exercises/series/examples/success-standard/src/Series.hs, exercises/series/package.yaml, exercises/series/test/Tests.hs
exercism/problem-specifications#1020
Note that the Haskell track will explicitly differ from the canonical
data in the following ways:
* slice length too long results in no slices, not an error.
* 0 length results in the appropriate number of zero-length slices, not
an error.
=> series 1.0.0.3: Add duplicates/long series; Expect (n+1) zero-length series; Change test from ab to 01 

exercises/pov/package.yaml, exercises/pov/test/Tests.hs
Some implementations choose to always use the root node, even when the
shortest path should not.
https://github.com/exercism/problem-specifications/pull/1227
=> pov 1.3.0.6: add test for paths not involving root

exercises/isbn-verifier/examples/success-standard/src/IsbnVerifier.hs, exercises/isbn-verifier/package.yaml, exercises/isbn-verifier/test/Tests.hs
Handles all three possible implementations:
* Truncate left
* Truncate right
* Consider all 11
https://github.com/exercism/problem-specifications/pull/993#issue-149955212
https://github.com/exercism/problem-specifications/issues/1199
https://github.com/exercism/problem-specifications/pull/1255
=> isbn-verifier 2.7.0.8: Replace too long case

exercises/sieve/examples/success-standard/src/Sieve.hs, exercises/sieve/src/Sieve.hs
This hopefully should make it clear when trial division is used instead of the proper algorithm.
For further readings, [this](https://www.cs.hmc.edu/~oneill/papers/Sieve-JFP.pdf) paper :)
=> sieve : Hint that trial division might be used

exercises/difference-of-squares/examples/success-standard/src/Squares.hs, exercises/difference-of-squares/package.yaml, exercises/difference-of-squares/src/Squares.hs, exercises/difference-of-squares/test/Tests.hs
In the exercise "difference-of-squares", I find the name `squareOfSums` weird, as it returns the square of a single sum. Maybe the name `squareOfSum` is more appropriate.
=> difference-of-squares: Rename squareOfSums to squareOfSum

exercises/nucleotide-count/examples/success-standard/src/DNA.hs, exercises/nucleotide-count/package.yaml, exercises/nucleotide-count/src/DNA.hs, exercises/nucleotide-count/test/Tests.hs
Preserve the Data.Map.
References #964
=> nucleotide-count: Use data type to represent nucleotides

README.md
We would like to document the versioning policy decided in
https://github.com/exercism/haskell/issues/522 and implemented in
https://github.com/exercism/haskell/pull/523
Closes https://github.com/exercism/haskell/issues/538
=> README: document exercises' versioning policy

exercises/forth/package.yaml, exercises/forth/test/Tests.hs
This was a mistake when applying 1.6.0; I accidentally used the same
test name for the two added tests!
https://github.com/exercism/haskell/pull/700
https://github.com/exercism/problem-specifications/pull/1243
=> forth 1.6.0.9: Replace duplicated test name with correct name

exercises/bob/examples/success-standard/package.yaml, exercises/bob/examples/success-standard/src/Bob.hs, exercises/bob/package.yaml, exercises/bob/test/Tests.hs
In the [Bob exercise](https://github.com/exercism/haskell/tree/master/exercises/bob) it says:
> Bob's conversational partner is a purist when it comes to written
> communication and always follows normal rules regarding sentence
> punctuation in English.
But in the unit test the following input is fed to `responseFor`:
"\nDoes this cryogenic chamber make me look fat?\nno"
This is a rhetorical question, and by the expected value, this is deemed
to not be an actual question, which is very reasonable. But if Bob's
conversational partner is a punctuation purist, it should at least be
"no." with the period.
I found this by wanting to grab the last character that `isPunctuation`,
but had to go with `not . isSpace` (like the reference solution). But
this really sounds wrong when I think about …
=> Bob's conversational partner is a purist!

exercises/phone-number/package.yaml, exercises/phone-number/test/Tests.hs
This should catch solutions with a validation function that calls itself recursively when the first digit is '1'.
Addresses exercism/problem-specifications#1325
=> phone-number 1.5.0.6: add cases to test data that cover invalid use of "1" or "0"

exercises/clock/.meta/hints.md, exercises/clock/README.md, exercises/clock/examples/success-standard/src/Clock.hs, exercises/clock/package.yaml, exercises/clock/src/Clock.hs
Ever since the clock exercise was implemented for Haskell track in
https://github.com/exercism/haskell/pull/12, the tests have never
required clockHour nor clockMin; it was an internal function used by the
example solution.
when stub was added for clock (and other exercises) in July 2016 in
https://github.com/exercism/haskell/pull/200 the clockHour and clockMin
were added to the stub.
It doesn't seem to make sense to include untested functions in the stub,
plus there does not seem to be any particular value in testing these
separately (rather than the current approach of just testing toString),
so the solution is to remove them.
=> clock 2.2.1.6: Remove clockHour and clockMin

exercises/perfect-numbers/package.yaml, exercises/perfect-numbers/test/Tests.hs
Two benefits:
* Make tests clearer to a reader of this file
* Prevent accidental ambiguity in imports (what if a PerfectNumbers
decides to include a `describe` function?)
=> perfect-numbers 1.1.0.3: Explicitly list imports of PerfectNumbers

exercises/complex-numbers/package.yaml, exercises/complex-numbers/test/Tests.hs
Two benefits:
* Make tests clearer to a reader of this file
* Prevent accidental ambiguity in imports (what if a ComplexNumbers
decides to include a `describe` function?)
=> complex-numbers 1.3.0.4: Explicitly list test's imports of ComplexNumbers

config.json
Perhaps I don't understand the policy of [TOPICS.txt](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt); some of the topics there would not make sense to add to Haskell exercises; e.g. recursion, pattern matching and polymorphism would appear excessively. But perhaps on the first exercise that aims to teach those it would make sense.
With that in mind I've added two topics.
=> Add topics to config.json

docs/ABOUT.md
I've tried to make the About page conform to [exercism/language-tracks/documentation/introductory-copy.md][1]:
- Slightly less detail.
- More readable to non-Haskellers.
- Shortened from ~200 words to ~160 words.
- Modelled on [the Go track][2]'s About page.
- Added links to LYAH and tryhaskell.org, Hackage, Stack.
- Preserved sentences one per line, but such that they render in fewer paragraphs.
It still does not mention history, design goals, or what Haskell is great for.
It no longer has comparisons to other languages. It could have.
[1]: https://github.com/exercism/docs/blob/master/language-tracks/documentation/introductory-copy.md#code-snippet
[2]: https://github.com/exercism/go/blob/master/docs/ABOUT.md
=> Improve about page

exercises/robot-name/.meta/hints.md, exercises/robot-name/README.md, exercises/robot-name/examples/fail-no-collision-testing/package.yaml, exercises/robot-name/examples/fail-no-collision-testing/src/Robot.hs, exercises/robot-name/examples/success-standard/package.yaml, exercises/robot-name/examples/success-standard/src/Robot.hs, exercises/robot-name/package.yaml, exercises/robot-name/src/Robot.hs, exercises/robot-name/test/Tests.hs
Altered the type signatures in the exercise, the testing suite and the example solution to use the StateT monad transformer.
=> Changing robot-name to use StateT

exercises/sum-of-multiples/package.yaml, exercises/sum-of-multiples/test/Tests.hs
**Edit:** This bumps version to 1.4.1, so it should be applied after #741, which bumps it to 1.4.0.
I apologize for being chronologically challenged. :-D
=> sum-of-multiples: describe the importance of each test (test version 1.4.1, closes #738)

config/maintainers.json
I suspect it may give a bit more hope to people if they don't see "0
maintainers".
=> maintainers: Show myself and my bio on the website

docs/INSTALLATION.md
Shortly described how GHC installation works with stack, and how to
check that GHC is installed correctly. Also added a "cautionary" note
about trying to run the Exercism exercises with a non-stack GHC (i.e.
might work, but stack is easiest).
=> Added a section on GHC installation.

exercises/clock/.meta/hints.md, exercises/clock/README.md, exercises/clock/examples/success-standard/src/Clock.hs
Since it's not necessary for the exercise or for testing, the `Show`
instance has been removed from the README.
Fixes #747.
=> Removed mention of `Show` from README.

exercises/pythagorean-triplet/README.md, exercises/pythagorean-triplet/examples/success-standard/src/Triplet.hs, exercises/pythagorean-triplet/package.yaml, exercises/pythagorean-triplet/src/Triplet.hs, exercises/pythagorean-triplet/test/Tests.hs
Replacing previous tests with isPythagorean (don't test intermediate
steps) and triplets in factor range (reasonable way to test, just not
what the canonical data chose to use)
Given the new restriction of `a < b < c` we no longer need `mkTriplet`
according to the previous rationale for keeping it (ordering):
https://github.com/exercism/haskell/pull/507#discussion_r106767328
https://github.com/exercism/problem-specifications/pull/1332
https://github.com/exercism/problem-specifications/pull/1365
=> pythagorean-triplet 1.0.0.3: Test only tripletsWithSum

exercises/robot-simulator/examples/success-standard/src/Robot.hs, exercises/robot-simulator/package.yaml, exercises/robot-simulator/src/Robot.hs, exercises/robot-simulator/test/Tests.hs
2.3.0: "Remove ambiguity" (show all parameters of the robot, even those
that don't change, which makes testing a bit of a pain)
exercism/problem-specifications#1333
3.0.0: Remove intermeditae functions, which means turnRight and turnLeft
for the Haskell track.
exercism/problem-specifications#1343
3.1.0: Renames the README case added in 3.0.0
exercism/problem-specifications#1357
=> robot-simulator 3.1.0.6: Remove turnLeft and turnRight

bin/test-example
I'm no longer able to run hspec 2.5.0 on at least one machine I own, for
Reasons (filesystems mounted noexec). Allow the environment variable
NOSTACK to signify not using Stack.
Slightly incomplete for `build` and `test`, but good enough for now.
=> test-example: support runghc without stack

exercises/bob/examples/success-text/package.yaml, exercises/bob/examples/success-text/src/Bob.hs, exercises/bob/test/Tests.hs
The only thing that is necessary for the test suite to support a
responseFor :: Text -> Text
is to assume that it has the type `IsString s => s -> s`.
We leave the stub as `String -> String`, but make the test suite compatible with the change. This means that mentors can suggest a solution based on `Data.Text` if they like. One case where that might make sense is when they refer to `Data.Text.strip`.
Exercise version bumped from 1.4.0.7 to 1.4.0.8.
=> bob 1.4.0.8: Make test suite compatible with `Data.Text`

exercises/allergies/examples/success-standard/package.yaml, exercises/allergies/package.yaml, exercises/allergies/src/Allergies.hs, exercises/allergies/test/Tests.hs
I was adding the `allergies` exercise to the Ocaml track and wanted to write some property-based tests for it, since that seemed quicker.
I found Ocaml's QCheck library hard to understand, so I decided to write them in Haskell and port them to Ocaml. I don't know if they're really needed here, since the coverage for this exercise is already quite fine. But here they are.
=> allergies: Property-based tests.

config.json, exercises/rna-transcription/examples/success-standard/src/DNA.hs, exercises/rna-transcription/package.yaml, exercises/rna-transcription/src/DNA.hs, exercises/rna-transcription/test/Tests.hs
Since `RNA Transcription` is currently the second core exercise that uses error-aware return types, it would make sense to practice `Either` as an alternative to `Maybe`.
This suggestion came as a consequence of the discussion in #761.
=> rna-transcription: Change from 'Maybe' to 'Either Char'

docs/LEARNING.md, docs/RESOURCES.md
These are used in the following:
https://exercism.io/tracks/haskell/learning
https://exercism.io/tracks/haskell/resources
There is a nice page header on those pages that say "Learning Haskell"
and "Useful Haskell Resources" respectively, making our headers
unnecessary.
Particularly useful because the previous header of RESOURCES was
"Recommended Learning Resources" which is against the purpose of
RESOURCES as stated in:
https://github.com/exercism/docs/blob/master/language-tracks/documentation/for-consumers.md#file-structure
https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/README.md#improve-product-facing-copydocumentation
=> docs: rm headings from LEARNING and RESOURCES

exercises/largest-series-product/examples/success-standard/package.yaml, exercises/largest-series-product/examples/success-standard/src/Series.hs
Gets rid of `Data.Maybe` and `Safe`.  Uses a `window` function comparable to the one from the `series` exercise.  Performs error handling via `Either`'s Monad instance.
In cooperation with @jrp2014 and @sshine. See #724 for the discussion that led to this example.
This resolves #724.
=> largest-series-product: Make example idiomatic

exercises/wordy/package.yaml, exercises/wordy/test/Tests.hs
In keeping with [1.3.0][], we want to test that this fails in an
expected way rather than an unexpected way.
[1.3.0]: https://github.com/exercism/problem-specifications/pull/1383
Specifically for Haskell, we want to make sure that this results in
`None` rather than accessing an out-of-bounds index due to always
assuming that the inputs will have at least three space-separated
elements (of the form "What is X...?").
https://github.com/exercism/problem-specifications/pull/1401
=> wordy 1.5.0.8: Test question `What is?` with no operands or operators

bin/ensure-readmes-are-updated.sh
I didn't want to beat you to it, @petertseng, since you offered to do this.
But I figured this would be a good exercise for me to get to know the maintainer pipeline.
Fixes build problem in #773.
=> Ensure readmes are updated

exercises/pangram/examples/success-text/package.yaml, exercises/pangram/examples/success-text/src/Pangram.hs, exercises/pangram/test/Tests.hs
This mimics the change made for bob in #760.
The only thing that is necessary for the test suite to support a
responseFor :: Text -> Text
is to assume that it has the type `IsString s => s -> s`.
We leave the stub as `String -> String`, but make the test suite
compatible with the change. This means that mentors can suggest a
solution based on `Data.Text` if they like.
Exercise version bumped from 1.4.1.8 to 1.4.1.9
=> pangram 1.4.1.9: Make test suite compatible with `Data.Text` (#780)

config.json, exercises/dnd-character/.meta/hints.md, exercises/dnd-character/README.md, exercises/dnd-character/examples/success-standard/package.yaml, exercises/dnd-character/examples/success-standard/src/DND.hs, exercises/dnd-character/package.yaml, exercises/dnd-character/src/DND.hs, exercises/dnd-character/stack.yaml, exercises/dnd-character/test/Tests.hs
This exercise was created in exercism/problem-specifications#1397.
It is a basic exercise in random generators, so the idea I had for the
Haskell track was to practice making QuickCheck generators rather than
simply use the standard random generator.
For this reason, QuickCheck is added as a root dependency.
=> dnd-character: add new exercise

config.json
Nucleotide Count has several reasonable implementations and learning goals. Mentor notes are made available in exercism/website-copy#654 and the discussion to replace some core track exercises is advanced in #761.
=> Replace difference-of-squares with nucleotide-count on core track

exercises/pangram/package.yaml, exercises/pangram/test/Tests.hs
Fail if the input stream was touched beyond the first occurrence of each letter.
Many standard solutions achieve this property without much effort, and some don't.
This test case notifies the student that a more optimal solution is within reach.
It is commented out by default:
> While `success-standard` passes this test, and a `String`-based
> `fail-too-eager` example fails as expected, `success-text` cannot easily
> succeed, even if is changed into using `Data.Text.Lazy`:
> 
> One can write a `Data.Text.Lazy as LT`-specific test:
> 
>     describe "isPangram" $ do
>       it "is lazy" $
>         isPangram (LT.fromChunks ["a...z", undefined]) `shouldBe` True
> 
> But when the input comes via `fromString :: IsString s => String -> s`,
> the implementation has little control of the …
=> pangram 1.4.1.10: Add test case: determine pangram lazily

exercises/bob/.meta/hints.md, exercises/bob/README.md, exercises/bob/package.yaml
Bob is the exercise that by far fits the use-case of `Data.Text` best.
It didn't come with any hints, so I've added a hint in two parts:
- One that is "You need to implement `responseFor :: String -> String`"
- One that elaborates on how to get started with `Data.Text` with some links on qualifying imports, adding extra dependencies and Haddock references to Data.Text.
This change addresses #780.
=> Bob: Add README hint for optional Data.Text extensions

README.md
Although the README listed the three types that were proposed and
accepted in https://github.com/exercism/haskell/issues/397, it failed to
explain when we would want to use each type.
We rectify this by explaining each type.
Checks the first box (consider/document/discuss) of
https://github.com/exercism/haskell/issues/783
=> README: Document the reasons/uses of each type of example

exercises/hamming/package.yaml, exercises/hamming/test/Tests.hs
This solution will pass all the current test cases but fail on the new one:
```
module Hamming (distance) where
distance :: String -> String -> Maybe Int
distance [] []         = Just 0
distance (x:xs) (y:ys)
| length(xs) /= length(ys) = Nothing
| x /= y = fmap (1 + ) (distance xs ys)
| x == y = distance xs ys
```
=> Hamming: Add a test case to avoid wrong recursion solution

.travis.yml
my notes: A part of #751, but worth evaluating on its own.
I think this will only save about 4 seconds since that is the amount of time I see attributed to the following section of Travis build logs such as https://travis-ci.org/exercism/haskell/jobs/499951245#L440
```
$ rvm use default [4.25s]
Using /home/travis/.rvm/gems/ruby-2.4.1
** Updating RubyGems to the latest compatible version for security reasons. **
** If you need an older version, you can downgrade with 'gem update --system OLD_VERSION'. **
```
original commit message below:
---
This should speed up builds as we don't have to update rubygems constantly.
=> travis: Change language to bash

exercises/pig-latin/.meta/hints.md, exercises/pig-latin/README.md, exercises/pig-latin/examples/success-text/package.yaml, exercises/pig-latin/examples/success-text/src/PigLatin.hs, exercises/pig-latin/package.yaml, exercises/pig-latin/test/Tests.hs
As in #760 (bob) and #788 (pangram), the only change necessary to support
translate :: Text -> Text
is to enable OverloadedStrings in the test suite.
We leave the stub as `String -> String`, but make the test suite
compatible with the change, and we provide an optional README hint
adapted from #794 (bob). This may encourage students to pursue a
solution based on `Data.Text`, and it relieves mentors from having to
give this hint.
Exercise version bumped from 1.2.0.6 to 1.2.0.7.
=> pig-latin: Make test suite compatible with `Data.Text`

config.json
**Edit:** *As @petertseng points out below, embed the reasons for deciding into the commit message. As a consequence, the pull request message is updated to reflect this change. This change consists of moving the arguments from the discussion at #798 to this message instead.*
---
As part of [The Track Anatomy Project][1], the Haskell core track is
restructured in #798 using @F3PiX'es multi-stage framework referred to
as "The Track Tool".
Since The Track Tool is still under development, it isn't documented
yet. But the execution of the first step can be viewed for other
languages, e.g. exercism/javascript#590.
---
Proposal:
- Switch "Bob" and "Pangram".
They're both about handling textual data.
Pangram has fewer gotchas, is quicker done, has more variations among
its alternative solutions, …
=> Switch order of current core exercises

config.json, exercises/resistor-colors/README.md, exercises/resistor-colors/examples/success-standard/package.yaml, exercises/resistor-colors/examples/success-standard/src/ResistorColors.hs, exercises/resistor-colors/package.yaml, exercises/resistor-colors/src/ResistorColors.hs, exercises/resistor-colors/stack.yaml, exercises/resistor-colors/test/Tests.hs
Problem Specification: https://github.com/exercism/problem-specifications/pull/1466
=> Implement Resistor Colors exercise

exercises/rna-transcription/.meta/hints.md, exercises/rna-transcription/README.md, exercises/rna-transcription/examples/success-standard/src/DNA.hs
Fixes #801, and finishes propagating changes from #762.
Also modified `mapM` in the example solution to `traverse`, since `traverse` is more general and preferred, and `mapM` is typically just defined as an alias for it.
=> rna-transcription: Improve README hint and example

config.json, exercises/binary-search/.meta/hints.md, exercises/binary-search/README.md, exercises/binary-search/examples/success-standard/package.yaml, exercises/binary-search/examples/success-standard/src/BinarySearch.hs, exercises/binary-search/package.yaml, exercises/binary-search/src/BinarySearch.hs, exercises/binary-search/stack.yaml, exercises/binary-search/test/Tests.hs
Finishing @samosaara's work, this implements the binary-search exercise on the Haskell track using `Data.Array` from the `array` package. This seems to be the preferred choice cf. the discussion at #615.
In addition, a number of changes were made:
- Unlock this after `collatz-conjecture` as the exercise deals with `Maybe`; placing it after the first exercise that deals with error handling seems natural.
- Set exercise version number to 1.3.0.0 and update test suite. This addresses exercism/problem-specifications#1399 (version 1.3.0).
- Add `ghc-options: -Wall` since #769.
- Export function as `find`. This is what problem-specification calls it.
- Generalise type signature in stub to better distinguish the type parameter for the index and the type parameter for the elements. One could …
=> binary-search: Add exercise (closes #615)

exercises/leap/package.yaml, exercises/leap/test/Tests.hs
Changes in `1.5.0`:
* Add new test case for `year divisible by 2, not divisible by 4 in common year`: https://github.com/exercism/problem-specifications/pull/1465
Changes in `1.5.1`:
* Remove `:` from test case description strings: https://github.com/exercism/problem-specifications/pull/1468
=> Update leap tests to 1.5.1

exercises/acronym/.meta/hints.md, exercises/acronym/README.md, exercises/acronym/examples/success-text/package.yaml, exercises/acronym/examples/success-text/src/Acronym.hs, exercises/acronym/test/Tests.hs
As part of #780, use `Data.Text` when appropriate.
And as in #760 (bob), #788 (pangram) and #805 (pig-latin), the only
change necessary to support
abbreviate :: Text -> Text
is to enable OverloadedStrings in the test suite.
We leave the stub as `String -> String`, but make the test suite
compatible with the change, and we provide an optional README hint
adapted from #805 (pig-latin). This may encourage students to pursue a
solution based on `Data.Text`, and it relives mentors from having to
give this hint.
Exercise version bumped from 1.6.0.9 to 1.6.0.10.
=> acronym: Make test suite compatible with `Data.Text` (#780)

exercises/isogram/.meta/hints.md, exercises/isogram/README.md, exercises/isogram/examples/success-text/package.yaml, exercises/isogram/examples/success-text/src/Isogram.hs, exercises/isogram/test/Tests.hs
As part of #780, use `Data.Text` when appropriate.
The only change necessary to support
isIsogram :: Text -> Bool
is to enable OverloadedStrings in the test suite.
We leave the stub as `String -> String`, but make the test suite
compatible with the change, and we provide an optional README hint
adapted from #805 (pig-latin). This may encourage students to pursue a
solution based on `Data.Text`, and it relieves mentors from having to
give this hint.
This example uses mono-traversable for monomorphic folding.
Exercise version bumped from 1.7.0.7 to 1.7.0.8.
=> isogram: Make test suite compatible with `Data.Text` (#780)

exercises/dnd-character/examples/success-standard/src/DND.hs, exercises/dnd-character/package.yaml, exercises/dnd-character/src/DND.hs
The name of the D&D character was provided as inspiration for populating the `Character` type with additional fields that may be relevant in some practical context.
But it doesn't serve a purpose, and the remaining abilities should also serve as inspiration. Having seen a few solutions default the name to `""`, the name should be removed in the context of this exercise.
=> dnd-character: Remove name property

exercises/etl/.meta/hints.md, exercises/etl/README.md, exercises/etl/examples/success-text/package.yaml, exercises/etl/examples/success-text/src/ETL.hs, exercises/etl/test/Tests.hs
The only change necessary to support
transform :: Map Int Text -> Map Char Int
is to enable OverloadedStrings in the test suite.
We leave the stub as `Map a String -> Map Char a`, but make the test suite compatible with the change, and we provide an optional README hint adapted from #812 (isogram). This may encourage students to pursue a solution based on `Data.Text`, and it relieves mentors from having to give this hint.
Exercise version bumped from 1.0.0.4 to 1.0.0.5
=> etl: Make test suite compatible with `Data.Text` (#780)

exercises/triangle/package.yaml, exercises/triangle/src/Triangle.hs
As @phlummox commented in 9f2d160753fc0cb0dbc2536cd937a4eb9978114f,
> [...] adding a type signature to triangleType seems to suggest [...]
> that the problem can be solved by implementing a function of that type.
As we cannot think of a solution with only `Num` and not either `Ord` or
`Eq`, we add `Ord` to the handout stub as this provides most flexibility.
=> triangle: Add `Ord` constraint to handout stub

docs/LEARNING.md
This resource was referenced in Haskell Weekly 164, 2019-06-19. It
amends the 2018 edition, and so both of these are added as resources.
They appear to address newcomers in particular.
=> Add "An opinionated beginner's guide to Haskell" as learning resource

exercises/connect/README.md, exercises/connect/examples/success-standard/src/Connect.hs, exercises/connect/package.yaml, exercises/connect/test/Tests.hs
The "obsolete" sentence says that the tests won't have spaces. Now it is unspecified, but it would be unclear if the README had spaces and the tests don't have spaces.
We remove spaces in tests:
https://github.com/exercism/haskell/blob/master/exercises/connect/test/Tests.hs#L19
Before deciding, must decide:
1. Change the tests to no longer remove spaces.
2. Keep both the README and tests as is, but insert a statement somewhere (hints.md, or the tests) telling students to be aware of the discrepancy.
3. Suggest to problem-specifications that no, really, they should reinstate the stipulation about spaces not being present.
4. Your suggestion here.
original commit msg:
---
The canonical test input is now similar to what is shown in the
description, but the description says it isn't.
Fixes …
=> Connect: remove obsolete sentence from description

.travis.yml, config.json
Want to prevent any invalid UUIDs from being entered.
Want to put this in configlet lint, but can't:
exercism/configlet#99
exercism/configlet#168
So it will go in individual tracks' .travis.yml for now.
It appears that the site will accept pretty much arbitrary strings as
UUIDs for now, but we want to make less work for ourselves when valid
UUIDs are required.
=> travis: reject invalid UUIDs

exercises/matrix/README.md, exercises/matrix/examples/success-standard/src/Matrix.hs, exercises/matrix/package.yaml, exercises/matrix/test/Tests.hs
The READMEs now have 1-based indices but the tests still have 0-based.
Before these can be merged, must decide between various solutions:
1. Change the tests to be one-indexed.
2. Maintain our own README with zero-based indices. You do this by placing the README we want in `.meta/description.md`. Not recommended.
* We cannot just use hints.md since that only allows additive changes. This is a modification of existing text, which hints.md does not support.
3. Keep both the README and tests as is, but insert a statement somewhere (hints.md, or the tests) telling students to be aware of the discrepancy.
4. Suggest to problem-specifications that no, really, they should go back to using zero-based indices.
5. Your suggestion here.
=> matrix 1.1.0.6: Use 1-based indices

exercises/saddle-points/README.md, exercises/saddle-points/package.yaml, exercises/saddle-points/test/Tests.hs
1.4.0: 1-based coordinates
exercism/problem-specifications#1429
1.5.0: fix an erroneous coordinate
exercism/problem-specifications#1434
Matches `Data.Matrix.getElem` from `matrix`:
https://hackage.haskell.org/package/matrix-0.3.6.1/docs/Data-Matrix.html#v:getElem
---
I think these commits make sense *not* to squash (and if I were merging them, I would not squash), but I will live if they are squashed.
=> saddle-points 1.5.0.8: use 1-based coordinates

config.json
Before continuing to restructure the Haskell core track in #798, this commit
adds more topics to the core exercises in particular. This should both make
the core track overview more indicative, and provide a better overview for
what to look for in replacement exercises.
The following topics were changed:
- `leap`: Add "guards". One recommended set of solutions split the three
predicates into each their guard. So while the exercise can be completed
adequately without the use of guards, one can anticipate trying them out.
- `space_age`: Replace "discriminated_unions" with "sum_types". This should
sound less academic. Because "discriminated_unions" is also used in `yacht`,
replace it there, too.
- `pangram`: Add "higher_order_functions". There is a number of acceptable
solution strategies …
=> Update topics for core exercises in config.json

exercises/diamond/examples/success-standard/package.yaml, exercises/diamond/examples/success-standard/src/Diamond.hs, exercises/diamond/package.yaml, exercises/diamond/test/Tests.hs
Here is the initial implementation for property-based tests for the `diamond` exercise. For any non-letter character `diamond` should produce `Nothing`. I am very open to feedback as I would like to contribute to this project.
To do:
=> Diamond: Implement property-based tests

exercises/resistor-color-duo/README.md, exercises/resistor-color-duo/examples/success-standard/src/ResistorColors.hs, exercises/resistor-color-duo/package.yaml, exercises/resistor-color-duo/test/Tests.hs
https://github.com/exercism/problem-specifications/pull/1569
=> resistor-color-duo 2.1.0.2: Ignore bands beyond the second

exercises/armstrong-numbers/package.yaml, exercises/armstrong-numbers/test/Tests.hs
Upgraded test to v1.1.0
exercism/problem-specifications#1505
=> armstrong-numbers: Bump test to version 1.1.0.3

exercises/leap/package.yaml, exercises/leap/test/Tests.hs
Upgrade leap to 1.6.0
added tests for exercism/problem-specifications#1581
=> Sync test leap 1.6.0

exercises/raindrops/.meta/hints.md, exercises/raindrops/README.md, exercises/raindrops/examples/success-text/package.yaml, exercises/raindrops/examples/success-text/src/Raindrops.hs, exercises/raindrops/test/Tests.hs
Issue: https://github.com/exercism/haskell/issues/841
=> Port raindrops test-suite to support Data.Text

exercises/bank-account/.meta/hints.md, exercises/bank-account/README.md
The [Concurrent Haskell](https://en.wikipedia.org/wiki/Concurrent_Haskell) wikipedia page has an in-depth example of  `Control.Concurrent.STM` and should guide the user in the right direction.
The second point links to the [STM](https://hackage.haskell.org/package/stm) package to point the user to `TVar`. Maybe this is too explicit?
Closes #799
=> Bank Account: extend hint with extra help

exercises/forth/package.yaml
I checked with the changes:
https://github.com/exercism/problem-specifications/commit/75f4c0a8c86cd5140dc5e8f29ebbd6e728bc5025
There seem to be no typos in the haskell test descriptions, hence just a version bump
=> forth: bump the version to 1.7.1 (no changes needed)

exercises/etl/package.yaml, exercises/etl/test/Tests.hs
It seems that only a version bump is necessary.
Latest changes to this problem:
- exercism/problem-specifications#1536
- exercism/problem-specifications#1575
=> etl: bump the version to 2.0.1 (no changes needed)

exercises/robot-simulator/package.yaml, exercises/robot-simulator/test/Tests.hs
Comparing the current tests (3.1.0.7) with the current canonical
version for this exercise (3.2.0), the descriptions and titles have
changed in the PR exercism/problem-specifications#1525
=> robot-simulator: bump version to 3.2.0 and update test titles

exercises/diamond/.meta/hints.md, exercises/diamond/README.md, exercises/diamond/examples/success-standard/package.yaml, exercises/diamond/package.yaml, exercises/diamond/test/Tests.hs
Add `Data.Text` support for `diamond` from #841
@sshine Should I just modify the `README.md` or add a `.meta/hints.md` similar to https://github.com/exercism/haskell/blob/master/exercises/bob/.meta/hints.md?
=> Initial diamond text support in test suite

exercises/pangram/package.yaml, exercises/pangram/test/Tests.hs
This PR updates the `pangram` tests original mentioned in https://github.com/exercism/haskell/issues/852
I found this commit https://github.com/exercism/problem-specifications/commit/f68b632f2578d9969074657d764b32f61f53c008 describing the recent changes to the tests. It seems that the descriptions are the only thing that changed. Is the goal to match the descriptions? Or match the canonical tests described in the specifications?
=> upgrade pangram tests to 2.0.0

exercises/twelve-days/.meta/hints.md, exercises/twelve-days/README.md, exercises/twelve-days/package.yaml, exercises/twelve-days/test/Tests.hs
This allows students to use `Data.Text` to solve the `twelve-days` exercise.
See #841
=> Allow for use of Data.Text with twelve-days exercise

config.json, exercises/resistor-color-trio/.meta/hints.md, exercises/resistor-color-trio/README.md, exercises/resistor-color-trio/examples/success-standard/package.yaml, exercises/resistor-color-trio/examples/success-standard/src/ResistorColors.hs, exercises/resistor-color-trio/examples/success-text/package.yaml, exercises/resistor-color-trio/examples/success-text/src/ResistorColors.hs, exercises/resistor-color-trio/package.yaml, exercises/resistor-color-trio/src/ResistorColors.hs, exercises/resistor-color-trio/stack.yaml, exercises/resistor-color-trio/test/Tests.hs
This adds the exercise from exercism/problem-specifications#1551.
In addition to the canonical exercise, this implementation extends:
- Add a "zero" test case (Black, Black, Black).
- Add a `Data.Text` hint in `.meta/hints.md`.
- Export both a `label` function *and* an `ohms` function: While the
exercise is mainly about printing a formatted string, this nudges
the student towards separating print and calculate.
- For totality, since `Resistor` allows expressing resistors in the
megaohm and gigaohm ranges, extend the exercise so that the correct
unit beyond kiloohms are returned.
- Extended unit tests are added, and coverage is described as such:
Canonical tests are marked with 'x'.
Extended tests are marked with 'y'.
Optional (commented out) tests are marked with 'z'.
```
Color       1, 2 …
```
=> resistor-color-trio: Add exercise (with extensions)

exercises/resistor-color-duo/.meta/hints.md, exercises/resistor-color-duo/README.md, exercises/resistor-color-duo/examples/success-standard/src/ResistorColors.hs, exercises/resistor-color-duo/package.yaml, exercises/resistor-color-duo/src/ResistorColors.hs, exercises/resistor-color-duo/test/Tests.hs
TL;DR:
- I don't think we should be teaching people to write functions like this.
- The less controversial action would be to reject this PR in favor of one
where either
value :: [Color] -> Maybe Int
value :: [Color] -> Either String Int
value :: [Color] -> Either ColorError Int
Quick chronological recap of PRs that provide necessary context:
- 2019-03-08: exercise created in exercism/problem-specifications#1466
- 2019-03-12: exercise ported to Haskell track in #808
- 2019-08-17: third-band test case and formulation "brown-green-violet should
return 15 too, ignoring the third color." + one other similar formulation
added to README.md in exercism/problem-specifications#1569.
- 2019-10-01: third-band test case added to Haskell track in #849.
When this exercise was ported to Haskell track, …
=> resistor-color-duo: Change to `value :: (Color, Color) -> Int`

exercises/connect/README.md, exercises/isbn-verifier/README.md, exercises/minesweeper/README.md, exercises/robot-name/README.md
This PR updates the README.md for
- `connect`: exercism/problem-specifications#1601
- `isbn-verifier`: exercism/problem-specifications#1616
- `minesweeper`: exercism/problem-specifications#1602
- `robot-name`: exercism/problem-specifications#1599
in four separate commits referencing these PRs respectively.
*Update:* I've added short descriptions in each commit summarizing each upstream PR.
This PR ~can either be merged or rebased~ should probably be merged.
=> connect, isbn-verifier, minesweeper, robot-name: Update exercise readmes

exercises/matrix/examples/success-standard/package.yaml, exercises/matrix/package.yaml, exercises/matrix/test/Tests.hs
Per #881, adds a QuickCheck test for the property that `shape . reshape dimension $ matrix == dimension` for all valid `dimension`/`matrix`.
Closes #881.
=> Add QuickCheck test for reshaping in "matrix" exercise

exercises/rotational-cipher/.meta/hints.md, exercises/rotational-cipher/README.md, exercises/rotational-cipher/examples/success-text/package.yaml, exercises/rotational-cipher/examples/success-text/src/RotationalCipher.hs, exercises/rotational-cipher/package.yaml, exercises/rotational-cipher/test/Tests.hs
Add `Data.Text` support for `rotational-cipher` exercise from https://github.com/exercism/haskell/issues/841.
This will allow students to use `Data.Text` to solve the `rotational-cipher` exercise.
=> Allow for use of Data.Text on rotational-cipher exercise

config.json
resistor-color-duo was added in #808.
resistor-color-trio was added in #869.
Yet there is no resistor-color. I argue that there shouldn't be.
A reasonable solution might look like
```haskell
data Color = ...
deriving (Eq, Enum, Bounded)
colorCode :: Color -> Int
colorCode = fromEnum
colors :: [Color]
colors = [minBound..]
```
which makes it approximately as simple as the gigasecond exercise which was marked as deprecated in #280 (decision made in #230). Still, if it is simply missing, it will appear as an exercise that is potentially implementable on https://tracks.exercism.io/haskell/master/unimplemented
Since a question was raised about this exercise once, marking it as foregone will limit further requests made in vain.
=> resistor-color: Mark exercise as foregone

exercises/forth/.meta/hints.md, exercises/forth/README.md, exercises/forth/examples/success-standard/src/Forth.hs, exercises/forth/package.yaml, exercises/forth/src/Forth.hs, exercises/forth/test/Tests.hs
To avoid colliding with `Control.Applicative.empty` when, for example, using applicative parsing that re-exports this library, the `empty` value is suggested renamed to `emptyState` which is unambiguous.
Bump version from 1.7.1.12 to 1.7.1.13.
This addresses all instances of the word "empty" in the exercise repository:
```
$ ack empty
examples/success-standard/src/Forth.hs
7:  , emptyState
65:emptyState :: ForthState
66:emptyState = ForthState
test/Tests.hs
7:import Forth (ForthError(..), emptyState, evalText, toList)
15:    let runTexts = fmap toList . foldM (flip evalText) emptyState
README.md
33:- `emptyState` returns an empty `ForthState`.
src/Forth.hs
8:  , emptyState
22:emptyState :: ForthState
23:emptyState = error "You need to implement this function."
.meta/hints.md
6:- …
```
=> Forth: Rename 'empty' to 'emptyState'

exercises/clock/.meta/DONT-TEST-STUB, exercises/clock/package.yaml, exercises/clock/src/Clock.hs
Clock is the last remaining exercise that has the .meta/DONT-TEST-STUB file because the type in the src/Clock.hs stub is not compatible with the test suite.
Other examples of exercises that were revised so that testing the stub became possible are listed in #466. The difference is that those all had `data` definitions, whereas Clock is ideally solved with a 'newtype' and an appropriate alias.
The DONT-TEST-STUB mechanism was added by @petertseng in #464 and in particular the commits
- 1d91ceb1af24be5c0f2f051e82e429d171515343 (Travis code)
- 342b932a79824a547c443dee741aa2f966f66b58 (Clock-specific)
The change made in this commit argues that since the example solution has `deriving Eq`, adding this to the stub *will* make the exercise a bit easier, but it still won't give away the central …
=> Clock: Add `deriving Eq` to stub to make it testable

exercises/bank-account/examples/success-standard/src/BankAccount.hs, exercises/bank-account/package.yaml, exercises/bank-account/test/Tests.hs
There were two major issues with those tests. First and foremost: they
were compiled without `-threaded`, meaning there was no actual
concurrency during the test runs, making the test that spawns twenty
threads meaningless.
Secondly, there's a behaviour that wasn't tested: if an account
exists, we expect increment and balance to never return
`Nothing`. That should only ever happen if the account is closed. This
commit therefore also adds a test that mixes increments and balance
checks to ensure all of them return `Just`.
This commit also increases the number of parallel threads to 50 (which
was the amount after which I could reliably make the tests fail on my
machine).
I have tried an alternative solution: use Control.Concurrent.QSemN to
release all threads "at the same time"; but since …
=> bank-account: Fixed tests

bin/fetch-configlet
Travis builds are failing because of fetch-configlet failures, as tracked in https://github.com/exercism/configlet/issues/173. This patch is a copy of https://github.com/exercism/cpp/pull/344, which fixed the cpp track.
=> Fix fetch-configlet.

exercises/dominoes/package.yaml, exercises/dominoes/test/Tests.hs
I found a case where a student's code would mistakenly use the same
domino in both ways. With their code, the chain
`[(1, 2), (2, 3), (2,1)]` would be considered valid, as they would
first match (1,2) with (2,3), then swap the domino and match (3,2)
with (2,1).
Surprisingly, none of the tests currently catch this, hence this
patch.
=> dominoes: added double-orientation test

exercises/dominoes/package.yaml, exercises/dominoes/test/Tests.hs
This is meant to discourage students from using a solution that simply
tries permutations of the domino chain.
=> dominoes: add long test with no solution

config.json, exercises/bob/.meta/hints.md, exercises/bob/README.md, exercises/leap/.meta/hints.md, exercises/leap/README.md
I' like to suggest to remove the hint to use guards from the Leap exercise and move it to the Bob exercise (where guards are one of learning goals anyway).
Rationale: Most students have prior knowledge of some imperative language, which emphasizes statements. Haskell as a functional language emphasizes expression, which is not intuitive at first glance. Many students use nested if-then-else and also guards don't encourage students to start thinking differently. Therefore, one of the first exercises shall put focus on pure expressions. When using guards it is unavoidable to have Boolean literals on the right-hand side, which is not a good style and is therefore sub-optimal for one of the first exercises.
=> Leap: Remove hint to use guards

exercises/luhn/package.yaml, exercises/luhn/test/Tests.hs
Changes included:
1. exercism/problem-specifications#1480: 1.4.0 to 1.5.0:
Change "055a 444 285" test into "055b 444 285" for subtle reasons.
New test name: using ascii value for doubled non-digit isn't allowed
2. exercism/problem-specifications#1500: 1.5.0 to 1.6.0:
Add test case: valid number with an odd number of spaces
3. exercism/problem-specifications#1635: 1.6.0 to 1.7.0:
Add test case: invalid long number with an even remainder
*(Edit by @sshine: Added short description of the addressed commits.)*
=> Luhn: Update tests to 1.7.0 (1 changed tests, 2 new tests)

exercises/nucleotide-count/package.yaml, exercises/nucleotide-count/test/Tests.hs
Bump version from 1.3.0.7 to 1.3.0.8.
This was created by @jitwit in #903 and accidentally closed by a force-push by me.
This closes #902.
=> nucleotide-count: use findWithDefault to accept sparse maps

exercises/clock/.meta/hints.md, exercises/clock/README.md
Closes #908 
I added a few things:
- Updated implementation lines to specifiy the type of clock, and that you can add or subtract both hours and minutes from it.
- Added descriptions for the remaining 2 functions: toString and fromHourMin
- Added a resource from learn you a haskell for creating and using custom types
- Added restrictions to not use the inbuilt data.dates package. I followed the format of other problems.
=> clock: Improve hint

exercises/grade-school/README.md, exercises/list-ops/README.md, exercises/luhn/README.md, exercises/minesweeper/README.md, exercises/palindrome-products/README.md, exercises/perfect-numbers/README.md, exercises/resistor-color-duo/README.md, exercises/robot-name/README.md, exercises/simple-cipher/README.md, exercises/simple-linked-list/README.md
individual commit messages (properly attributed to their authors) explain.
under no circumstances should this be squashed.
=> README updates from problem-specifications

exercises/change/examples/success-standard/src/Change.hs, exercises/list-ops/package.yaml, exercises/list-ops/test/Tests.hs
Currently it seems that the only reason why 'nightly' CI fails is because of a few HLint warnings:
https://travis-ci.org/github/exercism/haskell/jobs/743533300
This PR consists of two commits that change `flip const` into `const id`.
Since one file is a test/Tests.hs, the [SERIAL component](https://github.com/exercism/haskell/#exercise-versioning) is bumped.
=> Make nightly CI succeed

exercises/resistor-color-duo/.meta/hints.md, exercises/resistor-color-duo/README.md, exercises/resistor-color-duo/examples/success-standard/package.yaml, exercises/resistor-color-duo/examples/success-standard/src/ResistorColors.hs, exercises/resistor-color-duo/package.yaml, exercises/resistor-color-duo/src/ResistorColors.hs, exercises/resistor-color-duo/test/Tests.hs
This PR resumes the work of and closes #907.
#907 appears to not have "Allow edits by maintainers" enabled, so I cannot push any changes there.
The only difference that is not already discussed in the feedback of #907 is that `instance Arbitrary Color` was replaced with `forAll colorGen`. This removes the need for suppressing orphan instances and is generally a better way to express the relationship between properties and particular generators. For more background on this choice, read the parts of the FPComplete article [QuickCheck, Hedgehog, Validity](https://www.fpcomplete.com/blog/quickcheck-hedgehog-validity/) that isn't about shrinking.
This PR could be squash-merged since my commit message is a bit meta.
The important part is addressing the actual change of #907.
=> Add property tests to resistor-color-duo (remake)

bin/ensure-readmes-are-updated.sh
Otherwise, in the case where `which configlet` has empty output, then
the line `if [ ! -x $configlet ]` is results in `if [ ! -x ]`. Observe
the following:
$ cat a.sh
if [ ! -x ]; then
echo "NOT EXECUTABLE"
else
echo "EXECUTABLE"
fi
$ sh a.sh
EXECUTABLE
That means, were $configlet not quoted, configlet not being in the PATH
would mean that the script would proceed (not exit) with $configlet
being empty string. That eventually results in a "generate not found" on
line 38 (which starts with `$configlet generate`).
Compare to:
$ cat b.sh
if [ ! -x "" ]; then
echo "NOT EXECUTABLE"
else
echo "EXECUTABLE"
fi
$ sh b.sh
NOT EXECUTABLE
This is the correct behavior, so we must quote $configlet making
"$configlet".
=> ensure-readmes-are-updated: must quote $configlet

config/maintainers.json
Originally submitted in #962, but closed because of the deletion of fork.
It seems that the resignation is intended because the fork has been deleted and sshine left the Exercism GitHub organisation.
=> Mark sshine as alumnus

config/exercise_readme.go.tmpl, exercises/practice/crypto-square/examples/success-standard/src/CryptoSquare.hs, exercises/practice/crypto-square/test/Tests.hs, exercises/shared/.docs/help.md, exercises/shared/.docs/tests.md
Fixes https://github.com/exercism/haskell/issues/895. The canonical test data itself is fine; the problem was that the test suite was ignoring whitespace when comparing the actual result to the expected result.
(It's been a few months without a reply from the creator of that issue, so I figured it would be ok to fix it myself, since I ran into this today -- apologies if not!)
=> Check whitespace in Crypto Square exercise

exercises/practice/palindrome-products/.docs/instructions.append.md
=> palindrome-products: fix typo ("your" -> "you") in instructions

.github/labels.yml, .github/workflows/configlet.yml, .github/workflows/sync-labels.yml, .github/workflows/tests.yml
individual commit messages speak
for the Haskell track, the org-wide-files sync of https://github.com/exercism/org-wide-files/issues/155 must take the form of this PR, instead of #1051 .
=> workflows: use reusable workflows for configlet and sync-labels

exercises/practice/sgf-parsing/.meta/examples/success-standard/src/Sgf.hs, exercises/practice/sgf-parsing/test/Tests.hs
Individual commit messages speak.
=> sgf-parsing: Explain all current test cases + Add individual tests of escaping/whitespace behaviour

exercises/practice/word-count/.docs/instructions.md
With "ignored", it's unclear if punctuation separates the words or is just removed (relevant for the test case [handles cramped lists](https://github.com/exercism/haskell/blob/e04fc88d1027f72e37a0f140ffc6161be05051eb/exercises/practice/word-count/test/Tests.hs#L56)).
=> word-count: Less ambiguous punctuation rule

README.md
Adds concepts and concept exercises entries. 
Corrects folder structure to include concepts.
=> README: update for concept exercises

concepts/basics/about.md, concepts/basics/introduction.md, concepts/basics/links.json, docs/ABOUT.md, docs/LEARNING.md, exercises/concept/lucians-luscious-lasagna/.docs/hints.md, exercises/concept/lucians-luscious-lasagna/.docs/introduction.md, exercises/practice/space-age/.docs/instructions.append.md
The original [learnyouahaskell.com](http://learnyouahaskell.com/) has become a bit outdated, and moreover had some long standing issues. Therefore, an updated fork is maintained at [learnyouahaskell.github.io](https://learnyouahaskell.github.io/).
I changed every link to the original LYAH in the repo to point to the updated fork instead.
=> Link to updated fork of Learn You A Haskell

README.md, reference/concepts.md
- Updates reference/concepts with concepts already covered.
- Updates README to reflect current directory structure (closes #1085)
=> reference/concepts.md: Update concepts completed;  README: Add instructions.md and config.json to practice exercise structure

concepts/algebraic-data-types/.meta/config.json, concepts/algebraic-data-types/about.md, concepts/algebraic-data-types/introduction.md, concepts/algebraic-data-types/introduction.md.tpl, concepts/algebraic-data-types/links.json, config.json, exercises/concept/valentines-day/.docs/hints.md, exercises/concept/valentines-day/.docs/instructions.md, exercises/concept/valentines-day/.docs/introduction.md, exercises/concept/valentines-day/.meta/DONT-TEST-STUB, exercises/concept/valentines-day/.meta/config.json, exercises/concept/valentines-day/.meta/design.md, exercises/concept/valentines-day/.meta/exemplar/package.yaml, exercises/concept/valentines-day/.meta/exemplar/src/ValentinesDay.hs, exercises/concept/valentines-day/package.yaml, exercises/concept/valentines-day/src/ValentinesDay.hs, exercises/concept/valentines-day/stack.yaml, exercises/concept/valentines-day/test/Tests.hs, reference/concepts.md
First stab at introducing ADTs and the associated exercise (Valentines Day) to get the conversation and edits started.
=> Concept Algebraic Data Types with exercise

.github/labels.yml, CODE_OF_CONDUCT.md, bin/fetch-configlet
see individual commit messages.
these commits **MUST NOT** be squashed when merging
=> labels, CODE_OF_CONDUCT, fetch-configlet: sync from org-wide-files

exercises/concept/temperature/.docs/hints.md, exercises/concept/temperature/.docs/instructions.md
Hi, I was doing the `Temperature` exercise when I took a look on `HINTS.md` and felt like the formulas for each conversion was maybe swapped! This PR fixes that.
cc @pwadsworth
=> Fixes hints for temperature concept

exercises/practice/saddle-points/test/Tests.hs
The second test case does not play well with `head` on line 21, since using `head` on an empty list yields an error.
Use `head` only when the list is not empty.
=> saddle-points/test: Do not use head on empty list

exercises/practice/leap/.approaches/conditional-expression/content.md, exercises/practice/leap/.approaches/logical-expression/content.md
On the «[Leap approach: Logical expression](https://exercism.org/tracks/haskell/exercises/leap/approaches/logical-expression)» page, currently two links inside special blocks/admonitions aren't rendered. You can quickly find them by searching for `][`.
The fix is moving the references inside the blocks. See also [this forum thread](http://forum.exercism.org/t/link-references-in-special-blocks-admonitions-are-not-rendered/3803).
=> Fix links not rendering inside special blocks

exercises/practice/leap/.approaches/introduction.md
> One thing I noticed is that the `introduction.md` document should list the approaches under their own heading and with (an excerpt of) its code.
> See https://exercism.org/tracks/csharp/exercises/collatz-conjecture/dig_deeper for an example.
_Originally posted by @ErikSchierboom in https://github.com/exercism/haskell/issues/1139#issuecomment-1430881119_
@ErikSchierboom You meant this, right?
I think this document is now compliant with the (relevant section of the) [approaches building docs](https://exercism.org/docs/building/tracks/approaches#h-approaches-overview).
=> leap approaches: Present the approaches in the overview document

exercises/practice/largest-series-product/.docs/instructions.md, exercises/practice/largest-series-product/.docs/introduction.md, exercises/practice/largest-series-product/.meta/tests.toml, exercises/practice/largest-series-product/test/Tests.hs
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
=> Sync largest-series-product docs with problem-specifications

exercises/concept/pacman-rules/.docs/hints.md, exercises/concept/pacman-rules/.docs/instructions.md, exercises/practice/leap/.approaches/conditional-expression/content.md
The repo in a few places mentioned the nonexistent `Boolean` type. This commit replaces all these mentions with `Bool`.
I considered _`Bool`ean_ in some cases, but decided against it.
=> Consistency & correctness fix: `Boolean` -> `Bool`

.github/workflows/tests.yml
This PR updates GitHub Actions workflows to a specific version.
This ensures that the workflow will always run the same code, which makes your build _stable_.
It will also prevent a potential security issue where a tag could be replaced by a malicious commit without consumers being aware of it.
The PR updates each non-SHA based workflow reference with the SHA of the referenced version/tag, so the current behavior should not change.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas for more information.
=> CI: pin GitHub Actions workflows

.gitignore
`stack.yaml.lock` files are generated automatically when exercises are tested and during their development.
Alternatively we could exclude `*.lock` more generally, which I feel makes some sense but could also break in the future.
=> Exclude `stack.yaml.lock` files

config.json, exercises/practice/rational-numbers/.docs/instructions.md, exercises/practice/rational-numbers/.meta/config.json, exercises/practice/rational-numbers/.meta/examples/success-standard/package.yaml, exercises/practice/rational-numbers/.meta/examples/success-standard/src/RationalNumbers.hs, exercises/practice/rational-numbers/.meta/tests.toml, exercises/practice/rational-numbers/package.yaml, exercises/practice/rational-numbers/src/RationalNumbers.hs, exercises/practice/rational-numbers/stack.yaml, exercises/practice/rational-numbers/test/Tests.hs
Added a new Haskell practice exercise Rational Numbers based on the available problem specification.
=> Added Rational Numbers exercise

config.json, exercises/practice/affine-cipher/.docs/instructions.append.md, exercises/practice/affine-cipher/.docs/instructions.md, exercises/practice/affine-cipher/.meta/config.json, exercises/practice/affine-cipher/.meta/examples/success-standard/package.yaml, exercises/practice/affine-cipher/.meta/examples/success-standard/src/Affine.hs, exercises/practice/affine-cipher/.meta/examples/success-text/package.yaml, exercises/practice/affine-cipher/.meta/examples/success-text/src/Affine.hs, exercises/practice/affine-cipher/.meta/tests.toml, exercises/practice/affine-cipher/package.yaml, exercises/practice/affine-cipher/src/Affine.hs, exercises/practice/affine-cipher/stack.yaml, exercises/practice/affine-cipher/test/Tests.hs
Added a new Haskell practice exercise Affine Cipher based on the available problem specification.
=> Add Affine Cipher exercise

config.json, exercises/practice/satellite/.docs/instructions.md, exercises/practice/satellite/.meta/config.json, exercises/practice/satellite/.meta/examples/success-standard/package.yaml, exercises/practice/satellite/.meta/examples/success-standard/src/BinaryTree.hs, exercises/practice/satellite/.meta/examples/success-standard/src/Satellite.hs, exercises/practice/satellite/.meta/tests.toml, exercises/practice/satellite/package.yaml, exercises/practice/satellite/src/BinaryTree.hs, exercises/practice/satellite/src/Satellite.hs, exercises/practice/satellite/stack.yaml, exercises/practice/satellite/test/Tests.hs
Added a new Haskell practice exercise Satellite based on the available problem specification.
=> Added Satellite exercise

exercises/practice/phone-number/.docs/instructions.md, exercises/practice/phone-number/.meta/tests.toml, exercises/practice/phone-number/test/Tests.hs
This PR is to update the tests for the phone-numbers exercise. The tests which check for symbols or letters would result in false positives if the code ensures that the area code or exchange code begin with a digit in range 2-9.
This also updates the exercise description to match the problem-specification.
The example solution passes the updated tests, so no change was needed there.
The updated specs for "invalid when more than 11 digits" and "invalid when 9 digits" have no change since the Haskell tests don't check for an error message
=> Synchronized tests for phone-number exercise

config.json, exercises/practice/word-search/.docs/instructions.md, exercises/practice/word-search/.meta/config.json, exercises/practice/word-search/.meta/examples/success-standard/package.yaml, exercises/practice/word-search/.meta/examples/success-standard/src/WordSearch.hs, exercises/practice/word-search/.meta/tests.toml, exercises/practice/word-search/package.yaml, exercises/practice/word-search/src/WordSearch.hs, exercises/practice/word-search/stack.yaml, exercises/practice/word-search/test/Tests.hs
Added a new Haskell practice exercise Word Search based on the available problem specification.
=> Add Word Search exercise

config.json, exercises/practice/state-of-tic-tac-toe/.docs/instructions.md, exercises/practice/state-of-tic-tac-toe/.meta/config.json, exercises/practice/state-of-tic-tac-toe/.meta/examples/success-standard/package.yaml, exercises/practice/state-of-tic-tac-toe/.meta/examples/success-standard/src/StateOfTicTacToe.hs, exercises/practice/state-of-tic-tac-toe/.meta/tests.toml, exercises/practice/state-of-tic-tac-toe/package.yaml, exercises/practice/state-of-tic-tac-toe/src/StateOfTicTacToe.hs, exercises/practice/state-of-tic-tac-toe/stack.yaml, exercises/practice/state-of-tic-tac-toe/test/Tests.hs
Added a new Haskell practice exercise State of Tic-Tac-Toe based on the available problem specification.
=> Add State of Tic-Tac-Toe exercise

exercises/practice/parallel-letter-frequency/package.yaml
The new test runner (https://github.com/exercism/haskell-test-runner/pull/104) expects the `tests` section of `package.yaml` to be the last one and the `dependencies` list to be the bottom as it simply appends new dependencies to the bottom of the file using code injection.
This change ensures that this exercise will work correctly with the latest changes of the test runner.
=> Fix: Moved tests section to bottom of package.yaml to avoid issues with test-runner code injection
