- config.json
- connect/connect_test.hs
- connect/example.hs
This is an implementation of the new connect exercise (exercism/x-common#54).
> Add connect exercise

- SETUP.md
Also include example command line for executing tests.
> Link to Exercism Help in `SETUP.md`.

- sum-of-multiples/sum-of-multiples_test.hs
Adding test cases to Sum of Multiples as per exercism/exercism.io#2341.
> Add test cases to Sum of Multiples

- bank-account/example.hs
- binary-search-tree/example.hs
- custom-set/example.hs
- forth/example.hs
- forth/forth_test.hs
- gigasecond/gigasecond_test.hs
- linked-list/example.hs
- list-ops/ListOps.hs
- raindrops/example.hs
- robot-name/robot-name_test.hs
- saddle-points/example.hs
- say/example.hs
- wordy/example.hs
> compile without warnings on GHC 7.10.1

- .travis.yml
- _test/bootstrap.sh
> Get travis running on multiple versions of GHC

- docs/LEARNING.md
Edit text however you like. The key is linking to the Haskell learning Wiki, which (in my opinion) is already an excellent resource center for beginning Haskell.
> Add learning.MD

- docs/ABOUT.md
Hopefully, it provides a simple basic overview of what makes Haskell
interesting.
> Wrote an initial ABOUT.md for Haskell.

- exercises/scrabble-score/scrabble-score_test.hs
replacement shall be OXYPHENBUTAZONE
Closes #110
> scrabble-score: replace multibillionaire; it's too long

- exercises/queen-attack/.gitignore
I imagine this file is here accidentally. It caused confusion for me when working on the corresponding exercise as I have my solutions in a git repo.
> Remove errant .gitignore file

- .travis.yml
> travis: 7.10.1 -> 7.10.3

- exercises/sum-of-multiples/sum-of-multiples_test.hs
Add test case { "factors": [3, 5]
, "limit": 100
, "expected": 2318 }
Swap cases { "factors" : [7, 13, 17]
, "limit"   : 20
, "expected": 51 }
and { "factors" : [4, 6]
, "limit"   : 15
, "expected": 30 }
Closes #87
> sum-of-multiples: Update test cases to match x-common json file

- exercises/pov/pov_test.hs
Given a tree that must be reparented on node `x`, the tests used to
ensure that the former parent of `x` comes *after* the former children
of `x`. But there's no reason this should be the case, since in trees we
don't particularly care about the ordering of the children. (There are
some specialised trees for which it is the case, but this is not one of
those trees)
By comparing the sorted edge list, we allow either ordering.
Tested by ensuring that the example solution passes (it puts former
parent after former children), and that it still passes when using the
opposite ordering by modifying `(children g) ++ [reparented]` to instead
be `reparented : children g`.
Also tested to ensure that solutions that always return `Nothing` and
`Just (Graph x [])` return reasonable error messages. …
> pov: Test sorted edge list, not exact graph order

- exercises/robot-simulator/robot-simulator_test.hs
> robot-simulator: Add test cases for turning.

- exercises/custom-set/custom-set_test.hs
Add new cases from exercism/x-common/custom-set.json.
Remove redundant cases.
Reorder tests to match x-common.
Change test's names to match x-common.
Closes #136
Closes #141
> custom-set: Update to match x-common/custom-set.json.

- exercises/leap/leap_test.hs
- Three cases added
- Rewritten to reduce code repetition and make it more readable.
> leap: Tests rewritten to match x-common/leap.json

- README.md
sorry that I had to do it, but I guess that if I didn't, someone else would, and it may be good to pre-empt so that they get fixed fast.
> README: fixup spelling and grammar

- README.md
Explain that using *stack* to test exercises is an experimental feature.
Small fixes to a paragraph.
> readme: Two small corrections

- README.md
- SETUP.md
- docs/INSTALLATION.md
- docs/TESTS.md
- Rewrite `docs/INSTALLATION.md`.
- Rewrite `docs/TESTS.md`.
- Rewrite `README.md`.
- Rewrite `SETUP.md`.
> Transform exercises in Stack projects - Phase 3 - Creating the transitional documentation

- config.json
Move exercise `rna-transcription` between `hamming` and `space-age`.
Closes #191
> rna-transcription: Move exercise

- exercises/leap/package.yaml
- exercises/leap/test/Tests.hs
> leap: Rewrite tests to use hspec with fail-fast.

- exercises/accumulate/package.yaml
- exercises/accumulate/test/Tests.hs
> accumulate: Rewrite tests to use hspec with fail-fast.

- exercises/strain/package.yaml
- exercises/strain/test/Tests.hs
> strain: Rewrite tests to use hspec with fail-fast.

- exercises/hamming/package.yaml
- exercises/hamming/test/Tests.hs
> hamming: Rewrite tests to use hspec with fail-fast.

- exercises/space-age/package.yaml
- exercises/space-age/test/Tests.hs
- Rewrite to use hspec.
- Replace old tests by tests matching the json file.
> space-age: Rewrite tests to use hspec with fail-fast.

- exercises/phone-number/package.yaml
- exercises/phone-number/test/Tests.hs
> phone-number: Rewrite to use hspec with fail-fast.

- exercises/grade-school/package.yaml
- exercises/grade-school/test/Tests.hs
> grade-school: Rewrite tests to use hspec with fail-fast.

- exercises/word-count/package.yaml
- exercises/word-count/test/Tests.hs
> word-count: Rewrite tests to use hspec with fail-fast.

- exercises/anagram/test/Tests.hs
Related to exercism/x-common#308 from @petertseng.
> anagram: Update test cases to match json file.

- exercises/kindergarten-garden/package.yaml
- exercises/kindergarten-garden/test/Tests.hs
> kindergarten-garden: Rewrite tests to use hspec with fail-fast.

- exercises/triangle/src/Example.hs
- exercises/triangle/src/Triangle.hs
- exercises/triangle/test/Tests.hs
- Complete rewrite the test suite to match `x-common/triangle.json`.
- Fix the example solution to pass the new test suite.
- Fix the stub solution to match changes in `TriangleType`.
> triangle: Rewrite to match the new json file.

- exercises/bank-account/package.yaml
- exercises/bank-account/test/Tests.hs
> bank-account: Rewrite tests to use hspec with fail-fast.

- exercises/wordy/package.yaml
- exercises/wordy/test/Tests.hs
> wordy: Rewrite tests to use hspec with fail-fast.

- exercises/octal/package.yaml
- exercises/octal/test/Tests.hs
> octal: Rewrite tests to use hspec with fail-fast.

- exercises/linked-list/package.yaml
- exercises/linked-list/test/Tests.hs
> linked-list: Rewrite tests to use hspec with fail-fast.

- docs/INSTALLATION.md
Update INSTALLATION.md to mention the need of a recent Stack version.
Closes #272.
> documentation: Update documentation to install a recent stack version.

- config.json
- exercises/change/package.yaml
- exercises/change/src/Change.hs
- exercises/change/src/Example.hs
- exercises/change/stack.yaml
- exercises/change/test/Tests.hs
implementation of [change](https://github.com/exercism/x-common/tree/master/exercises/change) exercise for Haskell.
> new exercise: change

- exercises/raindrops/test/Tests.hs
Add test cases for 8, 27 and 3125.
Related to exercism/x-common#370.
> raindrops: Add new tests from exercism/x-common#370

- exercises/allergies/HINTS.md
- exercises/allergies/src/Allergies.hs
> allergies: Move hints to HINTS.md

- exercises/all-your-base/src/Example.hs
> all-your-base: Remove compatibility code.

- exercises/bank-account/src/Example.hs
> bank-account: Remove compatibility code.

- exercises/binary-search-tree/src/Example.hs
> binary-search-tree: Remove compatibility code.

- exercises/forth/test/Tests.hs
> forth: Remove compatibility code.

- exercises/gigasecond/package.yaml
- exercises/gigasecond/test/Tests.hs
> gigasecond: Remove compatibility code.

- exercises/hamming/test/Tests.hs
> hamming: Remove compatibility code.

- exercises/largest-series-product/src/Example.hs
> largest-series-product: Remove compatibility code.

- exercises/linked-list/src/Example.hs
> linked-list: Remove compatibility code.

- exercises/list-ops/test/Tests.hs
> list-ops: Remove compatibility code.

- exercises/matrix/test/Tests.hs
> matrix: Remove compatibility code.

- exercises/raindrops/src/Example.hs
> raindrops: Remove compatibility code.

- exercises/robot-name/test/Tests.hs
> robot-name: Remove compatibility code.

- exercises/saddle-points/src/Example.hs
> saddle-points: Remove compatibility code.

- exercises/say/src/Example.hs
> say: Remove compatibility code.

- exercises/sum-of-multiples/test/Tests.hs
> sum-of-multiples: Remove compatibility code.

- exercises/word-count/test/Tests.hs
> word-count: Remove compatibility code.

- exercises/wordy/src/Example.hs
- exercises/wordy/test/Tests.hs
> wordy: Remove compatibility code.

- exercises/binary-search-tree/HINTS.md
- exercises/binary-search-tree/src/BST.hs
> binary-search-tree: Move hints to HINTS.md

- exercises/grade-school/HINTS.md
- exercises/grade-school/src/School.hs
> grade-school: Move hints to HINTS.md

- exercises/matrix/HINTS.md
- exercises/matrix/src/Matrix.hs
> matrix: Move hints to HINTS.md

- exercises/linked-list/HINTS.md
- exercises/linked-list/src/Deque.hs
> linked-list: Move hints to HINTS.md

- exercises/meetup/HINTS.md
- exercises/meetup/src/Meetup.hs
> meetup: Move hints to HINTS.md

- exercises/robot-name/HINTS.md
- exercises/robot-name/src/Robot.hs
> robot-name: Move hints to HINTS.md

- exercises/robot-simulator/HINTS.md
- exercises/robot-simulator/src/Robot.hs
> robot-simulator: Move hints to HINTS.md

- exercises/simple-linked-list/HINTS.md
- exercises/simple-linked-list/src/LinkedList.hs
> simple-linked-list: Move hints to HINTS.md

- exercises/space-age/HINTS.md
- exercises/space-age/src/SpaceAge.hs
> space-age: Move hints to HINTS.md

- exercises/sublist/HINTS.md
- exercises/sublist/src/Sublist.hs
> sublist: Move hints to HINTS.md

- exercises/wordy/HINTS.md
- exercises/wordy/test/Tests.hs
> wordy: Move hints to HINTS.md

- exercises/nucleotide-count/src/Example.hs
> nucleotide-count: Remove compatibility code

- exercises/food-chain/test/Tests.hs
Previously, if there was a mismatch, the output would look like:
```
1) food-chain.song matches lines
expected: Just (4,"I know an old lady who swallowed a spider.")
but got: Just (4,"I know an old lady who swallowed a thing.")
```
It's not necessarily clear that the 4 in the output means "the mismatch
was at line 4".
Now the error reads:
```
1) food-chain.song matches lines
mismatch at line 4
expected: Just "I know an old lady who swallowed a spider."
but got: Just "I know an old lady who swallowed a thing."
```
> food-chain: Show clearer line-by-line match messages

- exercises/allergies/src/Example.hs
> allergies: Improve code based on HLint's suggestions.

- exercises/all-your-base/src/Example.hs
- exercises/all-your-base/test/Tests.hs
> all-your-base: Improve code based on HLint's sugestions.

- exercises/bob/src/Example.hs
> bob: Improve code based on HLint's suggestions.

- exercises/clock/test/Tests.hs
> clock: Improve code based on HLint's suggestions.

- exercises/custom-set/src/Example.hs
- exercises/custom-set/test/Tests.hs
> custom-set: Improve code based on HLint's suggestions.

- exercises/forth/src/Example.hs
- exercises/forth/test/Tests.hs
> forth: Improved code based on HLint's suggestions.

- exercises/hamming/src/Example.hs
> hamming: Improve code based on HLint's suggestions.

- exercises/matrix/test/Tests.hs
> matrix: Improve code based on HLint's suggestions.

- exercises/minesweeper/src/Example.hs
> minesweeper: Improve code based on HLint's suggestions.

- exercises/pascals-triangle/test/Tests.hs
> pascals-triangle: Improve code base on HLint's suggestions.

- exercises/go-counting/src/Counting.hs
- exercises/go-counting/src/Example.hs
> go-counting: Improve code based on HLint's suggestions.

- exercises/pig-latin/src/Example.hs
- exercises/pig-latin/test/Tests.hs
> pig-latin: Improve code based on HLint's suggestions.

- exercises/simple-cipher/src/Example.hs
> simple-cipher: Improve code based on HLint's suggestions.

- exercises/simple-linked-list/src/Example.hs
> simple-linked-list: Improve code base on HLint's suggestions.

- exercises/raindrops/src/Example.hs
> raindrops: Improved code based on HLint's suggestions.

- exercises/binary-search-tree/test/Tests.hs
> binary-search-tree: Improve code based on HLint's suggestions.

- exercises/beer-song/HINTS.md
- exercises/beer-song/src/Beer.hs
- exercises/beer-song/src/Example.hs
- exercises/beer-song/test/Tests.hs
- Add `HINTS.md` explaining that the exercise is about refactoring.
- Use lyrics from `x-common/exercises/beer-song/description.md`.
- Tests all lines, one by one, and then the entire song.
- Remove old tests checking verses.
- Add stub solution passing the tests.
- Patch example solution to work with the new tests.
Related to #301.
> beer-song: Rewrite tests and add working stub solution.

- exercises/pig-latin/test/Tests.hs
As in https://github.com/exercism/x-common/pull/411
> pig-latin: Add test for vowel followed by qu

- exercises/binary-search-tree/HINTS.md
- exercises/binary-search-tree/src/BST.hs
> binary-search-tree: change stub to be able to run the tests

- exercises/change/test/Tests.hs
> change: fix test suite to ignored output's order

- docs/LEARNING.md
Add other online learning sites and recent books.
> add other learning resources. minor text edits.

- exercises/bob/test/Tests.hs
Complies with:
* https://github.com/exercism/x-common/pull/449
* https://github.com/exercism/x-common/issues/428
* https://github.com/exercism/x-common/issues/441
> bob: remove Unicode characters

- exercises/sublist/test/Tests.hs
Complies with:
* https://github.com/exercism/x-common/pull/438
* https://github.com/exercism/x-common/issues/432
I would it find it unlikely that someone will take this approach in this
language, but that's OK, we can add it to be sure.
> sublist: Add same digits different numbers test

- exercises/scrabble-score/test/Tests.hs
https://github.com/exercism/x-common/issues/509
https://github.com/exercism/x-common/pull/516
> scrabble-score: Test entire alphabet

- exercises/etl/test/Tests.hs
https://github.com/exercism/x-common/pull/507
> etl: use cases from x-common

- .travis.yml
- README.md
- bin/test-all-examples
- bin/test-example
- bin/test-stub
- exercises/accumulate/examples/fail-reverse/package.yaml
- exercises/accumulate/examples/fail-reverse/src/Accumulate.hs
- exercises/accumulate/examples/success-standard/src/Accumulate.hs
- exercises/leap/examples/error-nosig/package.yaml
- exercises/leap/examples/error-nosig/src/LeapYear.hs
- exercises/strain/examples/fail-reverse/package.yaml
- exercises/strain/examples/fail-reverse/src/Strain.hs
Individual commits have explanations for each.
> travis: extract functionality to scripts; behave differently based on test type. accumulate: add fail-reverse example

- exercises/triangle/test/Tests.hs
reviewers: it is possible that this will be controversial. Please let me know if instead you think we should move to the new test model. I will not have time to do that.
> triangle: Add case of 2a == b + c, then mark divergence from x-common

- exercises/strain/src/Strain.hs
> strain: add variable names to the stub

- exercises/space-age/HINTS.md
typo corrected in HINTS.md
closes #455
> space-age: Typo in HINTS.md: typo corrected

- exercises/binary/src/Binary.hs
binary: add explicit arguments to stub functions
Related to issue #473.
> stubs: Add explicit arguments to binary function

- exercises/accumulate/src/Accumulate.hs
Accumulate: add explicit arguments to stub functions
Related to issue #473.
> stubs: Add explicit arguments to accumulate function

- exercises/anagram/src/Anagram.hs
Anagram: add explicit arguments to stub function
Related to issue #473.
> stubs: add explicit arguments to anagram function

- exercises/hamming/src/Hamming.hs
Related to #473 
I am also adding the type declaration for the `distance` function as I believe it helps us beginners even more :-)
> Hamming: Add explicit arguments to the stub functions

- exercises/atbash-cipher/src/Atbash.hs
- exercises/largest-series-product/src/Series.hs
- exercises/linked-list/src/Deque.hs
- exercises/list-ops/src/ListOps.hs
- exercises/luhn/src/Luhn.hs
- exercises/matrix/src/Matrix.hs
- exercises/minesweeper/src/Minesweeper.hs
- exercises/nth-prime/src/Prime.hs
- exercises/nucleotide-count/src/DNA.hs
- exercises/ocr-numbers/src/OCR.hs
- exercises/pascals-triangle/src/Triangle.hs
- exercises/phone-number/src/Phone.hs
- exercises/pig-latin/src/PigLatin.hs
- exercises/prime-factors/src/PrimeFactors.hs
Part of #473 
I also renamed arguments from some functions following https://github.com/exercism/xhaskell/pull/504#discussion_r105571421 and https://github.com/exercism/xhaskell/pull/504#discussion_r105571584
**Note:** Could we tick the master list (from #473) with the updated exercises?
PR #504 together with the current one cover up to `prime-factors` inclusive
> Add Explicit Args To Exercises - Part 2

- exercises/sieve/src/Sieve.hs
- exercises/simple-cipher/src/Cipher.hs
- exercises/simple-linked-list/src/LinkedList.hs
- exercises/sublist/src/Sublist.hs
- exercises/sum-of-multiples/src/SumOfMultiples.hs
- exercises/triangle/src/Triangle.hs
- exercises/wordy/src/WordProblem.hs
- exercises/zipper/src/Zipper.hs
Part of #473 
`zebra-puzzle` doesn't need refactor.
The [Simple Cipher](http://exercism.io/exercises/haskell/simple-cipher/readme) page contains a [link](https://upload.wikimedia.org/wikipedia/en/7/75/Caesar3.png) to an image which is broken.
> Add Explicit Args To Exercises - Part 4

- exercises/bracket-push/test/Tests.hs
> bracket-push: Fix test group name

- exercises/anagram/package.yaml
- exercises/anagram/test/Tests.hs
"multiple" are now specific about the number.
https://github.com/exercism/x-common/pull/671
> anagram 1.0.1.3: disambiguate test description

- exercises/change/package.yaml
- exercises/change/test/Tests.hs
target > coins, but still can't make:
https://github.com/exercism/x-common/pull/535
no unit (1) coins:
https://github.com/exercism/x-common/pull/620
> change 1.0.0.2: add cases from x-common

- exercises/run-length-encoding/package.yaml
- exercises/run-length-encoding/test/Tests.hs
https://github.com/exercism/x-common/pull/624
> run-length-encoding 1.0.0.2: add whitespace and lowercase

- exercises/largest-series-product/package.yaml
- exercises/largest-series-product/test/Tests.hs
https://github.com/exercism/x-common/pull/471
> largest-series-product 1.0.0.2: make simple case first, rm largest

- exercises/saddle-points/package.yaml
- exercises/saddle-points/test/Tests.hs
Canonical data added in https://github.com/exercism/x-common/pull/756
> saddle-points 1.0.0.2: follow x-common

- exercises/leap/package.yaml
- exercises/leap/test/Tests.hs
https://github.com/exercism/x-common/pull/463
> leap 1.0.0.2: explain criteria in descriptions, put in progress order

- exercises/matrix/package.yaml
> matrix: Bump version

- config/maintainers.json
> maintainers: Set rbasso as alumnus

- config.json
- exercises/diamond/README.md
- exercises/diamond/examples/success-standard/package.yaml
- exercises/diamond/examples/success-standard/src/Diamond.hs
- exercises/diamond/package.yaml
- exercises/diamond/src/Diamond.hs
- exercises/diamond/stack.yaml
- exercises/diamond/test/Tests.hs
Sorry for all this PRs, but I'm absolutely not hurry. But, there are to many unimplemented exercises on Haskell , makes me sad.
> Implementing diamond

- exercises/etl/README.md
- exercises/ocr-numbers/README.md
- exercises/pascals-triangle/README.md
- exercises/pov/README.md
- exercises/rna-transcription/README.md
- exercises/sgf-parsing/README.md
https://github.com/exercism/problem-specifications/pull/901
https://github.com/exercism/configlet/pull/85 (as-yet unreleased)
> Titles: capitalise initialisms, add punctuation

- exercises/sum-of-multiples/README.md
https://github.com/exercism/problem-specifications/pull/942
> sum-of-multiples: Remove a duplicated sentence in README

- exercises/all-your-base/package.yaml
- exercises/all-your-base/test/Tests.hs
- exercises/bowling/package.yaml
- exercises/bowling/test/Tests.hs
- exercises/change/package.yaml
- exercises/change/test/Tests.hs
- exercises/crypto-square/package.yaml
- exercises/crypto-square/test/Tests.hs
- exercises/dominoes/package.yaml
- exercises/forth/package.yaml
- exercises/forth/test/Tests.hs
- exercises/hamming/package.yaml
- exercises/hamming/test/Tests.hs
- exercises/isogram/package.yaml
- exercises/isogram/test/Tests.hs
- exercises/pascals-triangle/package.yaml
- exercises/pig-latin/examples/success-standard/src/PigLatin.hs
- exercises/pig-latin/package.yaml
- exercises/pig-latin/test/Tests.hs
- exercises/queen-attack/package.yaml
- exercises/rna-transcription/package.yaml
- exercises/rna-transcription/test/Tests.hs
- exercises/robot-simulator/package.yaml
- exercises/secret-handshake/package.yaml
- exercises/secret-handshake/test/Tests.hs
- exercises/sum-of-multiples/package.yaml
- exercises/sum-of-multiples/test/Tests.hs
- exercises/zipper/package.yaml
- exercises/zipper/test/Tests.hs
Missing in this PR:
* acronym 1.1.0 (I don't want to remove HTML yet)
* palindrome-products 1.0.0 (need to move to Maybe)
* list-ops 2.0.0 (this has been sitting for a while just too lazy to do everything)
> Follow problem-specifications canonical test changes

- exercises/beer-song/README.md
- exercises/meetup/README.md
- exercises/sum-of-multiples/README.md
Current procedure:
```
git format-patch $PREVIOUS_COMMIT -- exercises/*/description.md
vim *.patch
git checkout -b readme $PREVIOUS_COMMIT
git am *.patch
git rebase -i $PREVIOUS_COMMIT
```
`../configlet/bin/generate . && git cal --date="$(git --git-dir=../problem-specifications/.git show --format=%ai -s HEAD)" --author="$(git --git-dir=../problem-specifications/.git show --format='%an <%ae>' -s HEAD)" -m "$(git --git-dir=../problem-specifications/.git log --format=%B -n1 HEAD)"`
1195bd289d60de91a8c6c44a8c35a3671e326587
> Regenerate READMEs from problem-specifications commits

- exercises/forth/package.yaml
- exercises/forth/test/Tests.hs
https://github.com/exercism/problem-specifications/pull/979
> forth 1.4.0.6: Add tests for case-insensitivity

- exercises/binary-search-tree/package.yaml
- exercises/binary-search-tree/test/Tests.hs
https://github.com/exercism/problem-specifications/pull/940
> binary-search-tree 1.0.0.3: Add toList of equal element

- exercises/alphametics/package.yaml
- exercises/alphametics/test/Tests.hs
1.1.0: new test
https://github.com/exercism/problem-specifications/pull/1024
1.1.1: description
https://github.com/exercism/problem-specifications/pull/1045
1.2.0: input object
https://github.com/exercism/problem-specifications/pull/1035
> alphametics 1.2.0.4: Add test with 199 addends

- README.md
Moved in https://github.com/exercism/haskell/pull/556
https://github.com/exercism/meta/issues/5
> README: mv TRACK_HINTS to docs/EXERCISE_README_INSERT.md

- exercises/isbn-verifier/README.md
https://github.com/exercism/problem-specifications/pull/1116
> isbn-verifier: Write ISBN in all-caps

- config.json
- exercises/transpose/README.md
- exercises/transpose/examples/success-standard/package.yaml
- exercises/transpose/examples/success-standard/src/Transpose.hs
- exercises/transpose/package.yaml
- exercises/transpose/src/Transpose.hs
- exercises/transpose/stack.yaml
- exercises/transpose/test/Tests.hs
I implemented the transpose exercise for haskell.
> Implemented transpose exercise

- exercises/alphametics/examples/success-standard/src/Alphametics.hs
- exercises/bank-account/examples/success-standard/src/BankAccount.hs
- exercises/sgf-parsing/examples/success-standard/src/Sgf.hs
Easier for reader of code to understand where identifiers come from.
> alphametics, bank-account, sgf-parsing: List imports

- .travis.yml
Let's see where the time is going
> travis: Time tests

- exercises/pig-latin/README.md
https://github.com/exercism/problem-specifications/issues/1049
https://github.com/exercism/problem-specifications/pull/1171
> pig-latin: Explain rules with more detail

- exercises/crypto-square/README.md
- exercises/sieve/README.md
Almost nobody implements the proper algorithm, in favor of trial division.
I hope this description will make it clearer to the exercise taker!
> sieve: Clarify the algorithm is not trial division; crypto-square: Clarify rectangular output requirement

- .travis.yml
- bin/check-configlet-fmt.sh
- config.json
- config/maintainers.json
Result of configlet fmt.
See exercism/meta#95 
Created at ROSSConf. /cc @kytrinyx
> Reformat config files for reordering

- exercises/allergies/package.yaml
- exercises/allergies/test/Tests.hs
- exercises/atbash-cipher/package.yaml
- exercises/atbash-cipher/test/Tests.hs
- exercises/grade-school/package.yaml
- exercises/grade-school/test/Tests.hs
- exercises/isbn-verifier/package.yaml
- exercises/isbn-verifier/test/Tests.hs
- exercises/isogram/package.yaml
- exercises/isogram/test/Tests.hs
- exercises/list-ops/package.yaml
- exercises/list-ops/test/Tests.hs
- exercises/luhn/package.yaml
- exercises/luhn/test/Tests.hs
- exercises/pangram/package.yaml
- exercises/protein-translation/package.yaml
- exercises/rna-transcription/package.yaml
- exercises/rna-transcription/test/Tests.hs
- exercises/saddle-points/package.yaml
- exercises/saddle-points/test/Tests.hs
- exercises/sgf-parsing/package.yaml
- exercises/sgf-parsing/test/Tests.hs
- exercises/simple-cipher/package.yaml
- exercises/simple-cipher/test/Tests.hs
I think there's about 3.5 months' worth of changes to catch up on
> various exercises: Use problem-specifications versions

- exercises/queen-attack/test/Tests.hs
> queen-attack: Fix typo in Tests.hs

- docs/ABOUT.md
I've reformatted the about section and removed the code sample for the new formatting guidelines in v2 [issue #686]
> ABOUT: Reflow sentences for one sentence per line

- config.json
- Added core exercises
- Added missing topics
- Added unlocked_by for non-core
- Set four exercises as non-core but unlocked by default (bonus exercises)
- Added `auto_approve` for the first exercise (hello-world)
[Issue #686]
> Updated exercise data in config.json

- exercises/bob/package.yaml
- exercises/bob/test/Tests.hs
Prerequisite to #713.
Addresses exercism/problem-specifications#1293.
> bob: Bump test to version 1.3.0.6

- exercises/leap/package.yaml
- exercises/leap/test/Tests.hs
Addresses exercism/problem-specifications#1359 (not yet merged).
> leap-1.4.0: Add negative test: year divisible by 200, not divisible by 400

- exercises/sum-of-multiples/package.yaml
- exercises/sum-of-multiples/test/Tests.hs
Addresses exercism/problem-specifications#1362 (merged). See discussion there.
> sum-of-multiples-1.3.0: the only multiple of 0 is 0

- exercises/sum-of-multiples/package.yaml
- exercises/sum-of-multiples/test/Tests.hs
This addresses exercism/problem-specifications#1368.
> sum-of-multiples: Bump test to 1.4.0

- config.json
- exercises/palindrome-products/examples/success-standard/src/Palindromes.hs
- exercises/palindrome-products/package.yaml
- exercises/palindrome-products/src/Palindromes.hs
- exercises/palindrome-products/test/Tests.hs
Modified the palindromes functions to return `Nothing` when no palindrome is available, added canonical tests for this, and modified reference implementation.
> Palindrome products returns `Maybe`

- exercises/change/package.yaml
- exercises/forth/package.yaml
- exercises/grains/package.yaml
- exercises/largest-series-product/package.yaml
- exercises/ocr-numbers/package.yaml
- exercises/pascals-triangle/package.yaml
- exercises/phone-number/package.yaml
- exercises/queen-attack/package.yaml
- exercises/say/package.yaml
- exercises/wordy/package.yaml
Individual commit messages justify why it is OK to no-op
> no-op declare compliance with problem-specifications

- exercises/complex-numbers/package.yaml
- exercises/complex-numbers/test/Tests.hs
> Use rounding in complex-numbers tests

- exercises/leap/.meta/hints.md
- exercises/leap/README.md
While many students submit something with guards, some don't.
This provides learning material up-front.
I'd like to also wait for exercism/problem-specifications#1418 before merging this.
> Leap: Add link to guards to hints

- exercises/sgf-parsing/README.md
- exercises/sgf-parsing/package.yaml
- exercises/sgf-parsing/test/Tests.hs
> sgf-parsing 1.2.0.5: add test case for multiple properties; add description of SZ property

- exercises/list-ops/package.yaml
- exercises/list-ops/test/Tests.hs
Change:
* Add one test case for reversing nested list: https://github.com/exercism/problem-specifications/pull/1453
> Update list-ops to 2.4.0

- exercises/word-count/package.yaml
- exercises/word-count/test/Tests.hs
Added two tests:
* Multiple whitespace - https://github.com/exercism/problem-specifications/pull/1023
* Empty words - https://github.com/exercism/problem-specifications/pull/1446
> Upgrade word-count to v1.3.0

- exercises/pangram/package.yaml
- exercises/pangram/test/Tests.hs
* Add false negative (pangram with additional non-ASCII character)
* Add false positive (non-pangram with additional non-ASCII character)
Closes #824.
> test(pangram): Add false positive/negative

- exercises/bob/README.md
This addresses exercism/problem-specifications#1516.
> Bob: Update README.md: Clarify definition of question/shouting

- exercises/bob/.meta/hints.md
- exercises/bob/README.md
Fence marks were visible at exercism.io.
> Fix indentation for fenced block in bulleted list

- exercises/anagram/README.md
- exercises/difference-of-squares/README.md
- exercises/etl/README.md
- exercises/grains/README.md
- exercises/raindrops/README.md
- exercises/scrabble-score/README.md
- exercises/space-age/README.md
- exercises/word-count/README.md
a collection of several months' worth
These should be relatively uncontroversial.
A few other batches with some controversial ones are coming up.
do not squash
> READMEs from problem specifications

- exercises/word-count/package.yaml
- exercises/word-count/test/Tests.hs
word-count: Bump test to version 1.4.0.0
Added test for exercism/problem-specifications#1557
> Sync test word count 1.4.0

- exercises/clock/package.yaml
- exercises/clock/test/Tests.hs
Problem specifications change: https://github.com/exercism/problem-specifications/commit/b344762ece0c95ada4f157b3815900654974c727
> clock: update to version 2.4.0

- exercises/bob/.meta/hints.md
- exercises/bob/README.md
- exercises/dnd-character/.meta/hints.md
- exercises/dnd-character/README.md
- exercises/raindrops/.meta/hints.md
- exercises/raindrops/README.md
> Hackage links in Markdown files

- exercises/nucleotide-count/README.md
- exercises/resistor-color-duo/README.md
>  README updates from problem-specifications

- .github/workflows/tests.yml
- bin/ensure-stack-resolvers-are-synced.sh
- bin/warn-on-failure
- exercises/practice/hello-world/src/HelloWorld.hs
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
> 🤖 Simplify `hello-world` stub

- exercises/practice/space-age/.docs/instructions.append.md
Change 'Your' to 'You' in "Your can use the provided signature"
> space-age: change typo of "Your" to "You"

- exercises/practice/diamond/.meta/examples/success-text/package.yaml
- exercises/practice/diamond/.meta/examples/success-text/src/Diamond.hs
Low-effort, but it's just making sure the tests work with this type.
> diamond: Add Text example

- exercises/practice/palindrome-products/test/Tests.hs
Fixes https://github.com/exercism/haskell/issues/1023#
> palindrome-products: Correctly display time taken by tests

- .github/workflows/tests.yml
- bin/ensure-stack-resolvers-are-synced.sh
- bin/test-all-examples
- bin/test-example
- bin/test-stub
- concepts/basics/.meta/config.json
- concepts/basics/about.md
- concepts/basics/introduction.md
- concepts/basics/links.json
- config.json
- exercises/concept/lucians-luscious-lasagna/.docs/hints.md
- exercises/concept/lucians-luscious-lasagna/.docs/instructions.md
- exercises/concept/lucians-luscious-lasagna/.docs/introduction.md
- exercises/concept/lucians-luscious-lasagna/.meta/STUB-ALLOWED-TO-NOT-COMPILE
- exercises/concept/lucians-luscious-lasagna/.meta/config.json
- exercises/concept/lucians-luscious-lasagna/.meta/design.md
- exercises/concept/lucians-luscious-lasagna/.meta/exemplar/package.yaml
- exercises/concept/lucians-luscious-lasagna/.meta/exemplar/src/LuciansLusciousLasagna.hs
- exercises/concept/lucians-luscious-lasagna/package.yaml
- exercises/concept/lucians-luscious-lasagna/src/LuciansLusciousLasagna.hs
- exercises/concept/lucians-luscious-lasagna/stack.yaml
- exercises/concept/lucians-luscious-lasagna/test/Tests.hs
This adds a concept to start the Haskell learning path. 
Concepts discussed include syntax basics for constants/function declaration, comments, modules, and indentation.
First significant pull request, all feedback is welcome.
> Basic Concepts 1

- README.md
Closes https://github.com/exercism/haskell/issues/1056
> Mention about automated test-runner in readme

- reference/concepts.md
To do:
1. [x] delete irrelevant concepts
2. [x] translate remaining concepts
3. [ ] add missing concepts
> Adapt F# concepts

- reference/concepts.md
- reference/implementing-a-concept-exercise.md
- Addressed issue #1029: README: Document the expected directory structure of a concept exercise. 
- Corrected reference concept exercise directory structure.
- Changed concepts lists to lists of checkboxes and marker concepts already done.
> Reference updates

- exercises/practice/proverb/package.yaml
Adds
```
```
to package.yaml to close issue #1021
> proverb: add commented dependencies section to package.yaml

- config.json
- exercises/concept/pacman-rules/.docs/hints.md
- exercises/concept/pacman-rules/.docs/instructions.md
- exercises/concept/pacman-rules/.docs/introduction.md
- exercises/concept/pacman-rules/.meta/config.json
- exercises/concept/pacman-rules/.meta/design.md
- exercises/concept/pacman-rules/.meta/exemplar/package.yaml
- exercises/concept/pacman-rules/.meta/exemplar/src/PacmanRules.hs
- exercises/concept/pacman-rules/package.yaml
- exercises/concept/pacman-rules/src/PacmanRules.hs
- exercises/concept/pacman-rules/stack.yaml
- exercises/concept/pacman-rules/test/Tests.hs
This squashes the commits from PR #1093 that was not made against main.
> Add concept exercise Pac-Man Rules for booleans

- exercises/practice/ocr-numbers/test/Tests.hs
> ocr-numbers: fix spelling mistake in Tests.hs

- concepts/pattern-matching/.meta/config.json
- concepts/pattern-matching/about.md
- concepts/pattern-matching/introduction.md
- concepts/pattern-matching/links.json
- config.json
Completes #1094 by adding Pattern Matching concept.
> Pattern Matching concept

- exercises/practice/acronym/.meta/config.json
- exercises/practice/armstrong-numbers/.meta/config.json
- exercises/practice/binary/.meta/config.json
- exercises/practice/bowling/.meta/config.json
- exercises/practice/change/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/connect/.meta/config.json
- exercises/practice/dnd-character/.meta/config.json
- exercises/practice/food-chain/.meta/config.json
- exercises/practice/forth/.meta/config.json
- exercises/practice/grade-school/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/linked-list/.meta/config.json
- exercises/practice/list-ops/.meta/config.json
- exercises/practice/minesweeper/.meta/config.json
- exercises/practice/pig-latin/.meta/config.json
- exercises/practice/pov/.meta/config.json
- exercises/practice/simple-cipher/.meta/config.json
- exercises/practice/simple-linked-list/.meta/config.json
- exercises/practice/twelve-days/.meta/config.json
- exercises/practice/yacht/.meta/config.json
A number of practice exercises have minor changes
to the metadata. Mostly it's just punctuation in the blurbs, though there are a few other minor changes such as tweaks to source URLs or updating wording for clarity.
Since these should all be straight forward to review, I've taken the liberty of updating them all in a single PR.
> Sync metadata with problem-specifications

- exercises/practice/beer-song/.docs/instructions.md
- exercises/practice/binary-search-tree/.docs/instructions.md
- exercises/practice/bowling/.docs/instructions.md
- exercises/practice/connect/.docs/instructions.md
- exercises/practice/grains/.docs/instructions.md
- exercises/practice/isbn-verifier/.docs/instructions.md
- exercises/practice/list-ops/.docs/instructions.md
- exercises/practice/matching-brackets/.docs/instructions.md
- exercises/practice/meetup/.docs/instructions.md
- exercises/practice/say/.docs/instructions.md
- exercises/practice/wordy/.docs/instructions.md
Excluded from this synchonization run:
- `sgf-parsing`, because I do not feel familiar enough with it
- `grade-school`, because the new instructions are wrong for the Haskell track (at least for now)
> Sync docs with problem-specifications

- config.json
- exercises/practice/darts/.docs/instructions.md
- exercises/practice/darts/.meta/config.json
- exercises/practice/darts/.meta/examples/success-standard/package.yaml
- exercises/practice/darts/.meta/examples/success-standard/src/Darts.hs
- exercises/practice/darts/.meta/tests.toml
- exercises/practice/darts/package.yaml
- exercises/practice/darts/src/Darts.hs
- exercises/practice/darts/stack.yaml
- exercises/practice/darts/test/Tests.hs
Added a new Haskell practice exercise Darts based on the available problem specification.
> Add Darts exercise

- config.json
- exercises/practice/two-bucket/.docs/instructions.append.md
- exercises/practice/two-bucket/.docs/instructions.md
- exercises/practice/two-bucket/.meta/config.json
- exercises/practice/two-bucket/.meta/examples/success-standard/package.yaml
- exercises/practice/two-bucket/.meta/examples/success-standard/src/TwoBucket.hs
- exercises/practice/two-bucket/.meta/tests.toml
- exercises/practice/two-bucket/package.yaml
- exercises/practice/two-bucket/src/TwoBucket.hs
- exercises/practice/two-bucket/stack.yaml
- exercises/practice/two-bucket/test/Tests.hs
Added a new Haskell practice exercise Two Bucket based on the available problem specification.
https://forum.exercism.org/t/add-two-bucket-exercise/9920
> Add Two Bucket exercise

- config.json
- exercises/practice/game-of-life/.docs/instructions.md
- exercises/practice/game-of-life/.docs/introduction.md
- exercises/practice/game-of-life/.meta/config.json
- exercises/practice/game-of-life/.meta/examples/success-standard/package.yaml
- exercises/practice/game-of-life/.meta/examples/success-standard/src/GameOfLife.hs
- exercises/practice/game-of-life/.meta/tests.toml
- exercises/practice/game-of-life/package.yaml
- exercises/practice/game-of-life/src/GameOfLife.hs
- exercises/practice/game-of-life/stack.yaml
- exercises/practice/game-of-life/test/Tests.hs
Added a new Haskell practice exercise Game of Life based on the available problem specification.
> Add Game of Life exercise

- config.json
- exercises/practice/book-store/.docs/instructions.append.md
- exercises/practice/book-store/.docs/instructions.md
- exercises/practice/book-store/.meta/config.json
- exercises/practice/book-store/.meta/examples/success-standard/package.yaml
- exercises/practice/book-store/.meta/examples/success-standard/src/BookStore.hs
- exercises/practice/book-store/.meta/tests.toml
- exercises/practice/book-store/package.yaml
- exercises/practice/book-store/src/BookStore.hs
- exercises/practice/book-store/stack.yaml
- exercises/practice/book-store/test/Tests.hs
Added a new Haskell practice exercise Book Store based on the available problem specification.
> Add Book Store exercise
